### ISSUE TITLE
ZeroMQ 4.0 not supported by OpenCog

### ISSUE THREAD

**Issue by dbl001** [opencog/opencog#1601] opened 2015-05-07 15:18 UTC
Hi,
I'm getting build error(s) in opencog with Zeromq (version 4.1 and 4.2).
Any ideas?
E.g -
In file included from /home/ubuntu/opencog/opencog/spatial/3DSpaceMap/Octree3DMapManager.h:33:0,
                 from /home/ubuntu/opencog/opencog/spacetime/SpaceServer.h:51,
                 from /home/ubuntu/opencog/opencog/persist/file/SavingLoading.h:43,
                 from /home/ubuntu/opencog/opencog/persist/file/SavingLoading.cc:47:
/home/ubuntu/opencog/lib/zmq/zmq.hpp:566:47: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_connected(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                               ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:566:60: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_connected(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                            ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:567:53: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_connect_delayed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; 

                                                            
...

ubuntu@ip-10-0-1-240:~/opencog/build$ uname -a
Linux ip-10-0-1-240 3.13.0-49-generic #81-Ubuntu SMP Tue Mar 24 19:29:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ip-10-0-1-240:~/opencog/build$ cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Build type: Release
-- Looking for include file opencog/util/cogutil.h
-- Looking for include file opencog/util/cogutil.h - found
-- Found CogUtil version 2.0.1 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- Looking for include file opencog/atomspace/atomspace.h
-- Looking for include file opencog/atomspace/atomspace.h - found
-- Found AtomSpaced at /usr/local/lib/opencog/libatomspace.so
-- AtomSpace found.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105400 found.
-- Found Boost::program_options
-- Found Boost::math
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.35.0") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- GHC was found.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Found GTK3: gtk-3;gdk-3;atk-1.0;gio-2.0;pangocairo-1.0;gdk_pixbuf-2.0;cairo-gobject;pango-1.0;cairo;gobject-2.0;glib-2.0  
-- Guile (2.0.9 >= 2.0.0) was found.
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- link-grammar( >= 4.7.12) was not found. Make sure LINK_GRAMMAR_LIBRARY, LINK_GRAMMAR_INCLUDE_DIR and LINK_GRAMMAR_DATA_DIR are set.
-- Link Grammar missing: needed for the Viterbi parser.
-- Found MOSES library: /usr/local/lib/libmoses.so
-- MOSES was found.
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- OpenGL was found.
-- Found these protobuf libs: /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Protobuf was found.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7") 
-- Python libs found.
-- Found Cython: /usr/local/bin/cython (Required is at least version "0.19.0") 
-- Cython ( 0.22 >= 0.19.0) found.
-- Python destination dir found: /usr/lib/python2.7/dist-packages
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDLmain.a;/usr/lib/x86_64-linux-gnu/libSDL.so;-lpthread (found version "1.2.15") 
-- SDL was found.
-- SDL_gfx was found
-- Found Intel TBB
-- 
-- Found Tclsh: /usr/bin/tclsh (found version "8.6") 
-- Found TCL: /usr/lib/x86_64-linux-gnu/libtcl.so  
-- Could NOT find TCLTK (missing:  TK_LIBRARY TK_INCLUDE_PATH) 
-- Could NOT find TK (missing:  TK_LIBRARY TK_INCLUDE_PATH) 
-- TCL shell was found here: /usr/bin/tclsh
-- Valgrind Prefix: 
-- Found VALGRIND: /usr/include/valgrind  
-- VALGRIND was found.
-- VALGRIND devel headers found.
-- Found Xerces-C: /usr/lib/x86_64-linux-gnu/libxerces-c.so
--               : /usr/include
--        Version: 3.1.1
-- Found Xerces 3.1.1 -- /usr/lib/x86_64-linux-gnu/libxerces-c.so
-- XMLRPC was not found. Make sure the entries XMLRPC_* are set.
-- libxmlrpc missing: needed for ubigraph module.
-- Found ZeroMQ library: /usr/local/lib/libzmq.so
-- Detected ZeroMQ version number: 4.1.0
-- ZeroMQ was found.

-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 

The following components will be built:
-----------------------------------------------
   Attention        - Agents for attention allocation dynamics.
   Blopex           - BLOPEX block eigenvalue solver.
   Cython bindings  - Cython (python) bindings.
   Dim. Embedding   - Compute dimensional embedding of the AtomSpace.
   Doxygen          - Code documentation.
   Embodiment       - Architecture for embodiment.
   Learning Server  - Embodiment Learning.
   GTK Visualizer   - GTK3-based Atomspace Visualizer.
   Python tests     - Python bindings nose tests.
   Server           - The CogServer.
   Spatial          - Vizualisation of the 3D spacemap.
   TBB              - Intel TBB for multithreading.
   Unit tests       - Unit tests.
   ZMQ              - ZMQ-based OAC GUI reports, AtomSpace publisher module.

The following components WILL NOT be built:
-----------------------------------------------
   Ubigraph         - Visualisation of the AtomSpace.
   Viterbi          - Viterbi Parser for Link Grammar.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/opencog/build
ubuntu@ip-10-0-1-240:~/opencog/build$ make
Scanning dependencies of target json_spirit
[  0%] Building CXX object lib/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_reader.cpp.o
[  0%] Building CXX object lib/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_value.cpp.o
[  1%] Building CXX object lib/json_spirit/CMakeFiles/json_spirit.dir/json_spirit_writer.cpp.o
Linking CXX shared library libjson_spirit.so
[  1%] Built target json_spirit
Scanning dependencies of target blopex
[  1%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/fortran_matrix.c.o
[  1%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/lobpcg.c.o
[  1%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/multivector.c.o
[  2%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/temp_multivector.c.o
Linking C shared library libblopex.so
[  2%] Built target blopex
Scanning dependencies of target serial_driver
[  2%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/multi_vector.c.o
[  3%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/pcg_multi.c.o
[  3%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/serial_driver.c.o
Linking C executable serial_driver
[  3%] Built target serial_driver
Scanning dependencies of target statistics
[  5%] Building CXX object opencog/learning/statistics/CMakeFiles/statistics.dir/DataProvider.cc.o
[  5%] Building CXX object opencog/learning/statistics/CMakeFiles/statistics.dir/Probability.cc.o
[  5%] Building CXX object opencog/learning/statistics/CMakeFiles/statistics.dir/Entropy.cc.o
[  5%] Building CXX object opencog/learning/statistics/CMakeFiles/statistics.dir/InteractionInformation.cc.o
Linking CXX shared library libstatistics.so
[  5%] Built target statistics
Scanning dependencies of target dimensionalembedding
[  5%] Building CXX object opencog/learning/dimensionalembedding/CMakeFiles/dimensionalembedding.dir/DimEmbedModule.cc.o
Linking CXX shared library libdimensionalembedding.so
[  5%] Built target dimensionalembedding
Scanning dependencies of target embodiment_atom_types
[  5%] Generating opencog types
-- Atom type name: PetNode
-- Atom type name: AvatarNode
-- Atom type name: AccessoryNode
-- Atom type name: HumanoidNode
-- Atom type name: UnknownObjectNode
-- Atom type name: IsAcceptableSecondArgLink
-- Atom type name: OntologicalInheritanceLink
-- Custom atom type name specified: "WRLink"
-- Atom type name: WRLink
-- Atom type name: FrequencyLink
-- Atom type name: FeelingNode
-- Atom type name: PhraseNode
-- Atom type name: SpeechActTriggerNode
-- Atom type name: SpeechActSchemaNode
-- Atom type name: DialogNode
-- Atom type name: UtteranceNode
-- Atom type name: DefinedFrameNode
-- Atom type name: DefinedFrameElementNode
-- Atom type name: FrameElementLink
-- Atom type name: SimultaneousEquivalenceLink
[  5%] Built target embodiment_atom_types
Scanning dependencies of target spacetime_atom_types
[  5%] Generating opencog types
-- Atom type name: SpaceMapNode
-- Atom type name: ObjectNode
-- Atom type name: BlockEntityNode
-- Atom type name: StructureNode
-- Atom type name: ImaginaryStructureNode
-- Atom type name: TimeNode
-- Atom type name: AtTimeLink
-- Atom type name: LatestLink
-- Atom type name: BeforeLink
-- Atom type name: OverlapsLink
-- Atom type name: DuringLink
-- Atom type name: MeetsLink
-- Atom type name: StartsLink
-- Atom type name: FinishesLink
-- Atom type name: EqualsLink
-- Atom type name: AfterLink
-- Atom type name: OverlappedByLink
-- Atom type name: ContainsLink
-- Atom type name: MetByLink
-- Atom type name: StartedByLink
-- Atom type name: FinishedByLink
-- Atom type name: PredictiveImplicationLink
-- Atom type name: TailPredictiveImplicationLink
-- Atom type name: PredictiveAttractionLink
-- Atom type name: SimultaneousAndLink
-- Custom atom type name specified: "EventualSequentialAND"
-- Atom type name: EventualSequentialAND
-- Custom atom type name specified: "EventualSequentialImplication"
-- Atom type name: EventualSequentialImplication
[  5%] Built target spacetime_atom_types
Scanning dependencies of target PatternMiner
[  5%] Building CXX object opencog/learning/PatternMiner/CMakeFiles/PatternMiner.dir/Pattern.cc.o
[  6%] Building CXX object opencog/learning/PatternMiner/CMakeFiles/PatternMiner.dir/HTree.cc.o
[  6%] Building CXX object opencog/learning/PatternMiner/CMakeFiles/PatternMiner.dir/PatternMiner.cc.o
[  6%] Building CXX object opencog/learning/PatternMiner/CMakeFiles/PatternMiner.dir/PatternMinerBF.cc.o
[  6%] Building CXX object opencog/learning/PatternMiner/CMakeFiles/PatternMiner.dir/PatternMinerDF.cc.o
Linking CXX shared library libPatternMiner.so
[  6%] Built target PatternMiner
Scanning dependencies of target cogita
[  6%] Building CXX object opencog/nlp/chatbot/CMakeFiles/cogita.dir/CogitaConfig.cc.o
[  6%] Building CXX object opencog/nlp/chatbot/CMakeFiles/cogita.dir/IRC.cc.o
[  6%] Building CXX object opencog/nlp/chatbot/CMakeFiles/cogita.dir/go-irc.cc.o
[  7%] Building CXX object opencog/nlp/chatbot/CMakeFiles/cogita.dir/whirr-sockets.cc.o
Linking CXX executable cogita
[  7%] Built target cogita
Scanning dependencies of target nlp_atom_types
[  8%] Generating opencog types
-- Atom type name: WordNode
-- Atom type name: AnyNode
-- Atom type name: ReferenceLink
-- Atom type name: DocumentNode
-- Atom type name: SentenceNode
-- Atom type name: SentenceLink
-- Atom type name: ParseNode
-- Atom type name: ParseLink
-- Atom type name: WordInstanceNode
-- Atom type name: WordInstanceLink
-- Atom type name: SequenceLink
-- Atom type name: WordSequenceLink
-- Atom type name: SentenceSequenceLink
-- Atom type name: DocumentSequenceLink
-- Atom type name: FeatureNode
-- Atom type name: FeatureLink
-- Atom type name: LinkGrammarRelationshipNode
-- Atom type name: LinkGrammarDisjunctNode
-- Atom type name: DefinedLinguisticConceptNode
-- Atom type name: DefinedLinguisticRelationshipNode
-- Atom type name: PrepositionalRelationshipNode
-- Atom type name: WordSenseNode
-- Atom type name: WordSenseLink
-- Atom type name: PartOfSpeechNode
-- Atom type name: PartOfSpeechLink
-- Atom type name: LemmaNode
-- Atom type name: LemmaLink
-- Atom type name: HolonymLink
-- Atom type name: CosenseLink
-- Atom type name: SemeNode
-- Atom type name: SemanticRelationNode
-- Atom type name: InterpretationNode
-- Atom type name: InterpretationLink
-- Atom type name: SpecificEntityNode
-- Atom type name: LgConnectorNode
-- Atom type name: LgConnMultiNode
-- Atom type name: LgConnDirNode
-- Atom type name: LgConnector
-- Custom atom type name specified: "MSTConnector"
-- Atom type name: MSTConnector
-- Atom type name: LgSeq
-- Atom type name: LgAnd
-- Atom type name: LgOr
-- Atom type name: LgWordCset
-- Atom type name: LgLinkInstanceNode
-- Atom type name: LgLinkInstanceLink
-- Custom atom type name specified: "MSTLinkNode"
-- Atom type name: MSTLinkNode
-- Custom atom type name specified: "MSTDisjunctNode"
-- Atom type name: MSTDisjunctNode
[  8%] Built target nlp_atom_types
Scanning dependencies of target nlp-types
[  8%] Building CXX object opencog/nlp/types/CMakeFiles/nlp-types.dir/NLPTypes.cc.o
Linking CXX shared library libnlp-types.so
[  8%] Built target nlp-types
Scanning dependencies of target wsd
[  8%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o
[ 10%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeUtils.cc.o
[ 10%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/Mihalcea.cc.o
[ 10%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/MihalceaEdge.cc.o
[ 10%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/MihalceaLabel.cc.o
[ 11%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/NNAdjust.cc.o
[ 11%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/ParseRank.cc.o
[ 11%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/ReportRank.cc.o
[ 11%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseCache.cc.o
[ 12%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseRank.cc.o
[ 12%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseSimilarityLCH.cc.o
[ 12%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseSimilaritySQL.cc.o
[ 12%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/Sweep.cc.o
[ 13%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/WordSenseProcessor.cc.o
Linking CXX shared library libwsd.so
[ 13%] Built target wsd
Scanning dependencies of target savable
[ 13%] Building CXX object opencog/persist/file/CMakeFiles/savable.dir/CoreUtils.cc.o
[ 15%] Building CXX object opencog/persist/file/CMakeFiles/savable.dir/SavingLoading.cc.o
In file included from /home/ubuntu/opencog/opencog/spatial/3DSpaceMap/Octree3DMapManager.h:33:0,
                 from /home/ubuntu/opencog/opencog/spacetime/SpaceServer.h:51,
                 from /home/ubuntu/opencog/opencog/persist/file/SavingLoading.h:43,
                 from /home/ubuntu/opencog/opencog/persist/file/SavingLoading.cc:47:
/home/ubuntu/opencog/lib/zmq/zmq.hpp:566:47: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_connected(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                               ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:566:60: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_connected(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                            ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:567:53: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_connect_delayed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                     ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:567:66: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_connect_delayed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                                  ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:568:53: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_connect_retried(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                     ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:568:66: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_connect_retried(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                                  ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:569:47: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_listening(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                               ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:569:60: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_listening(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                            ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:570:49: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_bind_failed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                 ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:570:62: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_bind_failed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                              ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:571:46: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_accepted(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                              ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:571:59: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_accepted(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                           ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:572:51: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_accept_failed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                   ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:572:64: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_accept_failed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                                ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:573:44: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_closed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                            ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:573:57: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_closed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                         ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:574:50: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_close_failed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                  ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:574:63: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_close_failed(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                               ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:575:50: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_disconnected(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                  ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:575:63: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_disconnected(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                               ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:576:45: error: ‘zmq_event_t’ does not name a type
         virtual void on_event_unknown(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                             ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:576:58: error: ISO C++ forbids declaration of ‘event_’ with no type [-fpermissive]
         virtual void on_event_unknown(const zmq_event_t &event_, const char* addr_) { (void)event_; (void)addr_; }
                                                          ^
In file included from /home/ubuntu/opencog/opencog/spatial/3DSpaceMap/Octree3DMapManager.h:33:0,
                 from /home/ubuntu/opencog/opencog/spacetime/SpaceServer.h:51,
                 from /home/ubuntu/opencog/opencog/persist/file/SavingLoading.h:43,
                 from /home/ubuntu/opencog/opencog/persist/file/SavingLoading.cc:47:
/home/ubuntu/opencog/lib/zmq/zmq.hpp: In member function ‘void zmq::monitor_t::monitor(zmq::socket_t&, const char*, int)’:
/home/ubuntu/opencog/lib/zmq/zmq.hpp:495:17: error: ‘zmq_event_t’ was not declared in this scope
                 zmq_event_t* event = static_cast<zmq_event_t*>(zmq_msg_data (&eventMsg));
                 ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:495:30: error: ‘event’ was not declared in this scope
                 zmq_event_t* event = static_cast<zmq_event_t*>(zmq_msg_data (&eventMsg));
                              ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:495:50: error: expected type-specifier before ‘zmq_event_t’
                 zmq_event_t* event = static_cast<zmq_event_t*>(zmq_msg_data (&eventMsg));
                                                  ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:495:50: error: expected ‘>’ before ‘zmq_event_t’
/home/ubuntu/opencog/lib/zmq/zmq.hpp:495:50: error: expected ‘(’ before ‘zmq_event_t’
/home/ubuntu/opencog/lib/zmq/zmq.hpp:495:62: error: expected primary-expression before ‘>’ token
                 zmq_event_t* event = static_cast<zmq_event_t*>(zmq_msg_data (&eventMsg));
                                                              ^
/home/ubuntu/opencog/lib/zmq/zmq.hpp:495:89: error: expected ‘)’ before ‘;’ token
                 zmq_event_t* event = static_cast<zmq_event_t*>(zmq_msg_data (&eventMsg));
                                                                                         ^
make[2]: *** [opencog/persist/file/CMakeFiles/savable.dir/SavingLoading.cc.o] Error 1
make[1]: *** [opencog/persist/file/CMakeFiles/savable.dir/all] Error 2
make: *** [all] Error 2
ubuntu@ip-10-0-1-240:~/opencog/build$

**Comment by dbl001** [comment] 2015-05-07 19:59
OpenCog built with ZeroMQ4.0.5.

**Comment by linas** [comment] 2015-08-31 18:14
Pull request #1751 might have fixed this problem. Please test and confirm.

**Comment by hedayat** [comment] 2015-11-06 10:36
I can confirm that opencog builds against ZeroMQ 4.0.5 successfully. So the problem is most likely that of #1751

**Comment by linas** [comment] 2016-06-29 01:23
Closing, appears to be fixed, per last comment above.

**Closed by linas** 2016-06-29 01:23 UTC
Labels: rest, state:bug
