### ISSUE TITLE
MOSESPLNSynergyUTest is hanging

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#2629] opened 2017-03-10 08:47 UTC
The test MOSESPLNSynergyUTest is taking forever, on atomspace's sha = `5bd86057a Merge pull request #1158 from ngeiswei/FC-backcompatible`, and opencog's sha = `3dd862549 Merge pull request #2628 from AmeBel/a-fix`.

**Comment by AmeBel** [comment] 2017-03-10 08:53
Also, I get the following, while trying to run the backward chaining example
```scheme
scheme@(guile-user)> (use-modules (opencog))
scheme@(guile-user)> (load "moses-pln-synergy-bc.scm")
ERROR: In procedure cog-new-link:
ERROR: Throw to key `C++-EXCEPTION' with args `("cog-new-link" "Unexpected contents in TypedVariableLink\nExpected type specifier (e.g. TypeNode, TypeChoice, etc.), got VariableNode (/home/amen/hansonrobotics/
opencog/atomspace/opencog/atoms/core/VariableList.cc:262)\nFunction args:\n((TypedVariableLink\n   (VariableNode \"$V1\")\n   (VariableNode \"$V1Type\")\n)\n (TypedVariableLink\n   (VariableNode \"$V2\")\n   (
VariableNode \"$V2Type\")\n)\n (TypedVariableLink\n   (VariableNode \"$V3\")\n   (VariableNode \"$V3Type\")\n)\n)")'.

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> 
```

**Comment by ngeiswei** [comment] 2017-03-10 10:07
This one is normal as I haven't merged into the atomspace branches with some contentious commits that I need to discuss with Linas first. But it shouldn't interfere with the existing functionalities.

**Comment by ngeiswei** [comment] 2017-03-10 10:08
As for `MOSESPLNSynergyUTest`, I'm looking into it.

**Comment by linas** [comment] 2017-03-10 10:17
what's contentious? let me know in git issue or commit or email list.

**Comment by ngeiswei** [comment] 2017-03-10 10:18
I will, I'm just too focused on fixing what I've recently broken ATM.

**Comment by wenwei-dev** [comment] 2017-03-17 04:10
MOSESPLNSynergy uses all of the 16GB memory on CI server that makes other jobs very slow. I'll pause opencog CI job for now until it's fixed. 

16/36 Test #16: EntityRecorderUTest ..............   Passed    0.04 sec
      Start 17: AtomOcTreeUTest
17/36 Test #17: AtomOcTreeUTest ..................   Passed    0.08 sec
      Start 18: TimeSpaceAtomUTest
18/36 Test #18: TimeSpaceAtomUTest ...............   Passed    0.11 sec
      Start 19: AnaphoraTest
19/36 Test #19: AnaphoraTest .....................   Passed   16.38 sec
      Start 20: SuRealUTest
20/36 Test #20: SuRealUTest ......................   Passed   22.91 sec
      Start 21: MicroplanningUTest
21/36 Test #21: MicroplanningUTest ...............   Passed   25.45 sec
      Start 22: MOSESPLNSynergyUTest
Build timed out (after 20 minutes). Marking the build as aborted.
Build was aborted
Finished: ABORTED

**Comment by ngeiswei** [comment] 2017-03-17 07:32
Sorry for the inconvenience, I'm working on it.

**Comment by ngeiswei** [comment] 2017-03-17 09:48
The deduction rule seems responsible. Don't know why yet.

**Comment by ngeiswei** [comment] 2017-03-17 09:57
Looks like some of my new rules allow more crap to generated and then the deduction rule explodes the atomspace.

**Comment by ngeiswei** [comment] 2017-03-17 15:13
Guys, I've just temporary disabled it. Don't close the issue.

**Comment by ngeiswei** [comment] 2017-03-20 08:01
I think I understand the problem, lambda-closed-construction-rule is more generic and, in forward chaining mode blows up the atomspace (well this + subsequent deduction). Unless that's an immediate problem for you I'm gonna let this aside and get back to it after a few days or so.

**Comment by ngeiswei** [comment] 2017-03-21 16:19
Solved. I add a rule that does mere evaluation of existing lambda closed term instead of generating zillions of them.

**Comment by linas** [comment] 2017-04-03 06:35
Not solved for me ... it still runs forever.

Note that, on this particular computer, I don't have moses installed, so whatever this unit test is doing, its not testing moses ...

**Comment by ngeiswei** [comment] 2017-04-03 07:56
Takes 6 minutes on my Q9650, works but I don't think this long time is justified. Will look into. MOSES isn't required, BTW.

**Comment by linas** [comment] 2017-04-03 09:35
I killed it after 488 seconds on my super-low-end `Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz` which has a great battery life but terrible performance.  All the other tests run in under a second or two, except for surreal and microplanning which take a minute.

**Comment by ngeiswei** [comment] 2017-04-03 09:35
The problem comes from https://github.com/opencog/atomspace/commit/3f8e7a8be1 :-)

So working on it...

**Comment by linas** [comment] 2018-05-27 03:49
Closing. This runs in 12 seconds, on a normal desktop. I have nt tried to reproduce on the low-end machine; it might be running out of RAM on that one.

**Closed by linas** 2018-05-27 03:49 UTC
Labels: pln
