### ISSUE TITLE
CogServer losing requests - Messaging Problems

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#2828] opened 2017-07-14 05:05 UTC
The current language pipeline, which sends observe text requests via netcat to the CogServer and then later requests to parse sentences, is losing requests. The problem I saw:

1) Parses of the entire set of en-tranche-1 books had missing word pairs. Which pairs would be missing were indeterminate but in every parse of the whole I'd end up having at least some word pairs missing. I tried segmenting the data and smaller tests did not exhibit this behavior.

2) I traced this backwards to the beginning by implementing some checking routines in the C++ observation code in an effort to determine if the problem was in the mutual information processing step or the input side. Essentially, after adding the observation atoms, I then reload the relevant pairs to make sure they have been added. These checks revealed that on a sporadic and seemingly random basis sentences which had just been observed would not show up in an immediate subsequent check. 

3) Suspecting this might be related to too many threads (60) causing some bug under particular circumstances of heavy use of many threads, I changed the maximum threads from:

`unsigned int ConsoleSocket::_max_open_sockets = 60;`

to

`unsigned int ConsoleSocket::_max_open_sockets = std::thread::hardware_concurrency();`

and my checks passed. A subsequent parse later completed with no missing pair errors. This was the first time I had achieved this result. So changing the maximum number of threads masked or eliminated the proximate cause of the problem I was seeing.

However, there is no logical reasons why having this number be much higher than the number of cores should cause any problems. So there is still an open bug or problem with the CogServer and the mechanism of using netcat to send requests via text. I can reproduce the problem here but it takes hours of processing to reproduce it. I suspect it is due to a netcat timeout when threads are busy since netcat is used by the perl scripts processing the sentences.

**Comment by linas** [comment] 2017-07-15 01:32
How do you know that a word-pair is "missing"?  Certainly, the "ANY" language pipeline does not attempt to generate all possible pairs; it generates only some of them, randomly.   You can increase the sampling by editing the `relex-server-any.sh` file, and bumping up `-n16` to something larger, e.g. `-n72`.

Anyway, I'm quite unclear on how you can even know that some pair is missing.

Also, "most" word-pairs (more than half of them) are observed more than once, so even if you missed it once or twice, it almost doesn't matter: in the end, we are interested in the once that get observed hundreds of times.  So, are you saying that some word pairs should have been observed hundreds of times, and were observed zero times?

Note also: changing the timing at the front-end can expose or hide bugs in the SQL backend (for example) or the atomspace (for example). Perhaps, under certain kinds of loads, not every atom gets inserted into th atomspace.  Perhaps under certain kinds of loads, the count on the truth value does not get incremented.  There are unit tests for this, they do pass, so a bad atomspace is not a likely culprit.

In the SQL backend, to reduce the disk write load, there is some queue de-duplication code.  Perhaps its buggy. It has zero unit tests for it!! Writing one might be a very good idea, and might expose the bug.

Here's how it works: When the user wants to save an atom, they call the `store-atom` scheme function. The call snakes through the atomspace and ends up in the SQL backend, where the atom is appended to a write-back queue.  Thus, the call to `store-atom` returns immediately to the caller, so that the caller can do other things.

In the meanwhile, there's a collection of 8 or 12 or so threads servicing the writeback queue, trying to empty it whenever it is not empty.  Perhaps these are somehow dropping the ball? I don't recall if we have unit tests for the async store queue or not.

De-duplication works like this: if `store-atom` is called, and an atom is already in the queue, it is not placed in the queue a second time. This avoid multiple writes of the same atom.  This is implemented by using C++ `std::set` instead of `std::queue`.  There's no unit test. Perhaps this is buggy? 

You can alter this by shrinking the size of the write-back queue, making it tiny or even zero.   There is a sync flag that will make all writes synchronous (i.e. `store-atom` will not return until SQL has saved it to disk). This could be slowww. 

I kind-of doubt that the bug is in the SQL code, or that its in the atomspace ... but I also doubt that its in the console-socket. 

The console-socket code does have a unit test, and it passes.  Its called `ShellUTest` and it uses netcat to bombard the cogserver with requests.  You can modify `ShellUTest` to have it run longer, or to do more bombardment, or add a delay to make each request take longer to run...

**Comment by linas** [comment] 2017-07-15 01:35
Finally: there is yet another possibility: perhaps the guile evaluator is simply never called, or its called, but does not execute the code it was called with. The current guile-2.2.2 code is still plainly buggy, which I find disconcerting.

**Comment by bgoertzel** [comment] 2017-07-15 02:15
On Sat, Jul 15, 2017 at 9:32 AM, Linas Vepštas <notifications@github.com>
wrote:

> How do you know that a word-pair is "missing"? Certainly, the "ANY"
> language pipeline does not attempt to generate all possible pairs; it
> generates only some of them, randomly. You can increase the sampling by
> editing the relex-server-any.sh file, and bumping up -n16 to something
> larger, e.g. -n72.
>
> Anyway, I'm quite unclear on how you can even know that some pair is
> missing.
>
>
>
Because our version of the language-learning pipeline does not start with
random link parses, but rather starts by building links between all pairs
of words that occur within distance k of each other in an input sentence...

-- ben

**Comment by linas** [comment] 2017-07-15 18:53
> Because our version of the language-learning pipeline does not start with random link parses, but rather starts by building links between all pairs of words that occur within distance k of each other in an input sentence...

Eh? How do you accomplish that?

**Comment by linas** [comment] 2017-07-15 18:56
> Because our version of the language-learning pipeline does not start with random link parses, but rather starts by building links between all pairs of words that occur within distance k of each other in an input sentence...

I mean -- if this is Curtis's old code from a month ago, then it is known-buggy: it clearly fails multiple unit tests, and in particular, it fails unit tests that would explain this particular bug in it's full entirety.   If this is a bug report against that block of code, then this is clearly a "user error".

**Comment by inflector** [comment] 2017-07-17 08:24
> if this is Curtis's old code from a month ago, then it is known-buggy: it clearly fails multiple unit tests.

This is not using any of the multi-threading changes I sent out earlier. The tests which exhibit the problem outlined in this issue use the atomspace master branch not any revisions.

You highlighted some issues which caused me to not use the branch code which segregated the mutex in the atom table until I have time to address the issues you highlighted.

The code for this issue is much simpler. This test just creates a list of word pair atoms for each sentence in a fairly large corpus like en-tranch-1 or simple English wikipedia. 

As a second step for each sentence, test code using the same algorithm tests to see if the created atoms are actually present in the atomspace. 

There is no guile involved here at all. It uses the same mechanisms as the current NLP pipeline, i.e. bash .sh scripts calling perl functions which call Requests using netcat. 

The problematic pieces are:

1) Bash to perl - could be hiding some failure or error in a perl script that isn't being logged or detected via an error condition.
2) Perl to Netcat to Cogserver Request - an error could exist causing requests not to be created for some netcat calls by the perl script.
3) Request processing in the CogServer - a request could be queued but then some internal bug loses the atom creation or eats some error quietly.

**Comment by linas** [comment] 2017-07-18 04:55
OK.  Not sure what to do, my pants are on fire with other issues. As a temporary work-around, reducing `max_open_sockets` to 30 or even 10 is OK by me.  I picked 60 hoping that it could hold for the next 5+ years when intel/amd come out with 256-core cpus. 

p.s. I should mention that my tranche-1 contains 12 sci-fi texts that are not publicly available, and my tranche-3,4,5 seem to have downloaded only about 2/3rds of the texts that they scripts should have downloaded.  Right now that's not a big deal, but it means that my results aren't perfectly reproducible.  I don;'t think it matters; they all seem to get close.

Off-topic, I should mention that the sentences in gutenberg are really really long, those in the scifi and fanfic are really short, and so, for the same quantity of text, have a 10x difference in parse speed.

**Comment by linas** [comment] 2017-07-20 16:10
FYI, just now I discovered that one of my databases does not contain a value that it should contain.  It was computed, it should have been stored. Its not there. The error is extremely rare: (1) its never happened before, and (2) I loaded a subsection of the database, consisting of 21M atoms.  During processing, circa about the 10'millionth atom, the desired value was missing.  I refetched the atom in question, the data is still missing, so presumably its not in the database, i.e. did not get stored. Foo.

**Comment by linas** [comment] 2017-09-08 00:09
I'm currently debugging a situation where scheme expressions sent via socket are sometimes not evaluated. ... or rather, their evaluation is delayed until the scheme evaluator is recycled a second time.   This is most easily reproduced with the irc chatbot; something about that is exposing some race condition somewhere.

**Comment by linas** [comment] 2017-09-08 01:13
Closing. I believe that #2879 fixes this;  please open a new bug report if anything like this is seen again.

**Closed by linas** 2017-09-08 01:13 UTC
Labels: nlp

**Comment by linas** [comment] 2017-09-08 01:23
Hmm. But of course, immediately after closing this, and merging master, I thought I would retest one last time, and the problem still occurs. Debugging now.

**Comment by linas** [comment] 2017-09-08 02:02
OK, so maybe pull req #2880 is also needed to fix this.
