### ISSUE TITLE
Chatbot fails to connect

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#2420] opened 2016-09-07 10:21 UTC
I have a cogserver running and I `guile -l run-chatbot.scm`. It works rather well and outputs

> $1 = "Started CogServer"

I then try the "sniff-test", 

```
rlwrap telnet localhost 17004
   (process-query "luser" "Are you a bot?")
```

and it fails with

> command "scm" not found
> command "(process-query" not found

I try the same in the guile shell running the `run-chatbot.scm`, and it outputs 

> ice-9/boot-9.scm:106:20: In procedure #<procedure 3972f40 at ice-9/boot-9.scm:97:6 (thrown-k . args)>:
> ice-9/boot-9.scm:106:20: In procedure connect: Connection refused

If I try `(nlp-parse "The sky is blue.")` after that, it just errors

> ERROR: In procedure connect:
> ERROR: In procedure connect: Connection refused

What's causing all this?

**Comment by linas** [comment] 2016-09-10 02:29
The `command "scm" not found` indicates that the cogserver was compiled without guile support in it. (Or that somehow, the guile module for the server could not be loaded.

Verify that, when you run "cmake ..", that it reports that guile is being built.

**Comment by StrangeTcy** [comment] 2016-09-10 15:13
Not exactly like that, but `cmake ..` reports that
```
-- Guile (2.0.11 >= 2.0.0) was found.
````
and after that that
```
The following components will be built:
-----------------------------------------------
   Attention        - Agents for attention allocation dynamics.
   Blopex           - BLOPEX block eigenvalue solver.
   Cython bindings  - Cython (python) bindings.
   Dim. Embedding   - Compute dimensional embedding of the AtomSpace.
   Doxygen          - Code documentation.
   GTK Visualizer   - GTK3-based Atomspace Visualizer.
   Python tests     - Python bindings nose tests.
   REST             - REST Atomspace Publisher module.
   Server           - The CogServer.
   Unit tests       - Unit tests.
   NLP              - Natural Language Processing.
   PatternMiner     - Pattern Miner.

```

`make` starts working and then at `[33%] Building CXX object` it outputs a lot of `note`s, which end with
```
opencog/nlp/fuzzy/CMakeFiles/nlpfz.dir/build.make:86: recipe for target 'opencog/nlp/fuzzy/CMakeFiles/nlpfz.dir/FuzzySCM.cc.o' failed
make[2]: *** [opencog/nlp/fuzzy/CMakeFiles/nlpfz.dir/FuzzySCM.cc.o] Error 1
CMakeFiles/Makefile2:1349: recipe for target 'opencog/nlp/fuzzy/CMakeFiles/nlpfz.dir/all' failed
make[1]: *** [opencog/nlp/fuzzy/CMakeFiles/nlpfz.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```
I guess that make doesn't proceed to properly making cogserver with guile support?

**Comment by StrangeTcy** [comment] 2016-09-10 16:29
When I run `./opencog/cogserver/server/cogserver -c ../lib/development.conf` and later `rlwrap telnet localhost 17001`, I can `opencog> scm` and then, say, `guile>(use-modules (opencog))`.
Does that mean that guile support is enabled?

**Comment by linas** [comment] 2016-09-10 16:55
guile is built as a part of the atomspace, not part of opencog.

I've never seen the fuzzy matcher fail to build, it should be fine.  The fuzzy matcher is used by the chatbot, so you will need it.

after telneting to 17001, things like `(+ 2 2)` should also work. The `guile>(use-modules (opencog))` is redundant at the telnet line.

**Comment by StrangeTcy** [comment] 2016-09-14 02:22
Update: newly made atomspace and opencog, same `guile -l run-chatbot.scm`.

Simple thing like `opencog>(+ 2 2)` work all right.

`guile -l run-chatbot.scm` runs successfully, but when I try to `(process-query "linas" "Are you a bot?") from the guile shell that opens, it still fails to connect; the exact first message is this:
```
Backtrace:
In system/vm/trap-state.scm:
 172: 19 [with-default-trap-handler #f ...]
In ice-9/boot-9.scm:
1724: 18 [%start-stack #t #<procedure 2a23510 at system/repl/repl.scm:189:14 ()>]
1729: 17 [#<procedure 2a233f0 ()>]
 157: 16 [catch quit #<procedure 2a233c0 at system/repl/repl.scm:191:18 ()> ...]
In system/repl/repl.scm:
 201: 15 [#<procedure 2a233c0 at system/repl/repl.scm:191:18 ()>]
In ice-9/boot-9.scm:
 157: 14 [catch #t ...]
In system/vm/trap-state.scm:
 172: 13 [with-default-trap-handler #<procedure debug-trap-handler (frame trap-idx trap-name)> ...]
In ice-9/boot-9.scm:
1724: 12 [%start-stack #t #<procedure 2a35600 at system/repl/repl.scm:202:32 ()>]
1729: 11 [#<procedure 2a354e0 ()>]
In system/repl/repl.scm:
 158: 10 [with-stack-and-prompt #<procedure 18edf40>]
In ice-9/boot-9.scm:
1724: 9 [%start-stack #t #<procedure 18edac0 at system/repl/repl.scm:159:33 ()>]
1729: 8 [#<procedure 2a35480 ()>]
 171: 7 [with-throw-handler #t ...]
In opencog/nlp/chatbot/bot-api.scm:
  39: 6 [#<procedure 2a353c0 at opencog/nlp/chatbot/bot-api.scm:37:8 ()>]
In opencog/nlp/chatbot/chat-utils.scm:
 262: 5 [nlp-parse "Am I a bot?"]
In opencog/nlp/processing-utils.scm:
  80: 4 [relex-parse "Am I a bot?"]
In unknown file:
   ?: 3 [connect #<input-output: socket 15> 2 2130706433 4444]
In ice-9/boot-9.scm:
 102: 2 [#<procedure 18b5d80 at ice-9/boot-9.scm:97:6 (thrown-k . args)> system-error ...]
In opencog/nlp/chatbot/bot-api.scm:
  83: 1 [#<procedure 1b9f240 at opencog/nlp/chatbot/bot-api.scm:82:8 args> system-error ...]
In unknown file:
   ?: 0 [backtrace #<undefined>]

Sorry, I caught an exception
ice-9/boot-9.scm:106:20: In procedure #<procedure 18b5d80 at ice-9/boot-9.scm:97:6 (thrown-k . args)>:
ice-9/boot-9.scm:106:20: In procedure connect: Connection refused

```

I haven't yet understood what it's trying to connect to. Is there a way to see its connection attempts?

**Comment by linas** [comment] 2016-09-14 03:14
well, if you read the stack trace, it will tell you what the problem is.

so for example its telling you to look at line 262 of nlp/chatbot/chat-utils.scm:  which then called line 80 of processing-utils.scm and it you look at line 80 of that file, you will see clearly that it is trying to do some tcpip i/o to some server called the relex server.
```
(connect s AF_INET (inet-pton AF_INET relex-server-host) relex-server-port)
```
My guess is that your relex server is not running.

You would have a lot less trouble with this system, if you actually carefully read through all of the various instructions, and thought about what they meant, and double-checked to see if you've done them, if they mattered or not.  I get the general impression that you are just racing through these, just skimming them, and then falling down.  Its like trying to go down stairs three-at-a-time, you are going to keep falling down, until you get a lot more practice.

**Comment by StrangeTcy** [comment] 2016-09-14 12:06
It was, but it was running on a non-standard port (since I've edited the `relex/opencog-server.sh`).
I tried to find out what config the chatbot uses to find the relex server port, but haven't yet.

I see how you get such an impression. I'm trying to pay more attention to the whole system.

**Comment by linas** [comment] 2016-09-14 16:58
Here's another command-line tool worth knowing: grep:
```
grep -r relex-server-port *
```

**Comment by linas** [comment] 2016-11-02 18:55
Closing, this seems to be resolved.

**Closed by linas** 2016-11-02 18:55 UTC
