### ISSUE TITLE
Guile modules naming convention

### ISSUE THREAD

**Issue by pennachin** [opencog/opencog#2682] opened 2017-04-07 19:56 UTC
While debugging the Chatlang unit test (which didn't work without `sudo make install`, see #2673, #2679, #2681) I ran into this issue. According to this:

https://www.gnu.org/software/guile/manual/html_node/Modules-and-the-File-System.html

a module in path `foo/bar/baz.scm` should be named `(foo bar baz)` so it will be found by guile when searching the load path. E.g., `(opencog nlp relex2logic)` and most of our modules. But a few  don't follow that convention, such as  `(opencog ato pointmem)`, `(opencog eva-behavior)`, and `(opencog eva-model)`. There may be others, I didn't run an exhaustive search; these are the ones I ran into.

The CMake files specify install instructions and paths, so the installed scheme files end up with the proper structure, but that explains why the modules can't be found before installing. Does it make sense to rename them?

**Comment by AmeBel** [comment] 2017-04-08 09:11
- For non scheme-bingding modules there is a cmake function [ADD_GUILE_MODULE](https://github.com/opencog/opencog/blob/master/lib/OpenCogFunctions.cmake) that creates a symlink in the `/opencog/build/opencog/scm` directory similar to the install path. 

- For scheme-binding modules, as per https://github.com/opencog/opencog/pull/2679#issuecomment-292592067, there are some utilities @ https://github.com/opencog/opencog/blob/master/opencog/cogserver/scm/config.scm that can be used with https://github.com/opencog/opencog/blob/master/lib/development.conf

**Comment by linas** [comment] 2017-04-09 10:57
The ato pointmem stuff if just broken. all the space-time server junk is broken, and someone needs to go in there and fix it.

The eva-behavior and eva-model install into `/usr/local/share/opencog/scm/opencog` on my machine, which is exactly where they should be.  So there should be no problem there.

**Comment by linas** [comment] 2017-04-09 10:59
For chatlang,  I would recommend installing it as `(opencog chatlang)`  seems like an OK spot, to me...

**Comment by linas** [comment] 2017-04-09 11:01
There is no expectation anywhere that anything at all can even remotely work until it is installed. The user MUST install to get a usable system.  In particular, the unit tests are guaranteed to fail if you try to compile or run them before performing an install. You MUST install before compiling the unit tests.

**Comment by leungmanhin** [comment] 2017-04-10 12:07
I'm not sure what is the best way to fix this kind of issues... I personally prefer to install before testing, and Amen helped to updated the ocpkg https://github.com/opencog/ocpkg/pull/84 accordingly so it should now be passing in docker container as well. But if this is not the best practice maybe we could try come up with some other solutions

**Comment by pennachin** [comment] 2017-04-17 14:30
Yeah, the tests pass on the container after installing. 

The main issue is why the unit tests require installing before running, which may be fine for people who are actively working on OpenCog itself -- they're going to have an installed system anyway, and if the latest build is broken they probably know how to fix it or know enough to determine the current breakage doesn't affect their work.

People trying OpenCog for the first time or those building applications that use OpenCog as a dependency, on the other hand, shouldn't have to install a potentially broken build just to verify whether it's broken. This is hostile to new community members. Of course, the traditional solution to this problem is to have a set of tests one can run before installation... This is how unit tests work pretty much everywhere. 

At least one very simple fix would be to follow Guile's convention for finding modules while structuring source directories (e.g. everything under `opencog/nlp` seems to do that) so ADD_GUILE_MODULE can find those files without further magic. If we aren't going to follow Guile's convention for the eva modules, I wonder if there's a way to make ADD_GUILE_MODULE work? @AmeBel, thoughts? Manipulating the cogserver config doesn't make sense, the tests can't require a cogserver...

**Comment by linas** [comment] 2017-04-17 19:24
The problem is that the way in which one wants to organize source code does not in general match up how one wants to organize API's.  The needs and demands of the two conflict, and trying to find a one-size-fits-all solution is a search for that straight-jacket that is comfortable to wear. This a generic issue for all coding projects, not just opencog.

**Comment by pennachin** [comment] 2017-04-17 21:20
Yeah, that's a good point on code organization in general, and the main reason I'm trying to explore how to make ADD_GUILE_MODULE work is that I don't want to pester you about how you organize your source files...

**Comment by AmeBel** [comment] 2017-04-18 04:58
@cassiopennachin  I agree on the point you raised on the cogserver utility. I just wanted to point that the statements in the utilities can be used to write tests, which would run without having to install.

I will look into expanding the ADD_GUILE_MODULE to accommodate eva modules.

**Comment by AmeBel** [comment] 2017-04-19 09:18
@pennachin @linas please review https://github.com/opencog/opencog/pull/2694

**Comment by AmeBel** [comment] 2017-04-19 09:22
I have tested locally without installing and all the scheme tests pass. 

If the pr is merged, should I live the changes made @ https://github.com/opencog/ocpkg/pull/84/files#diff-ac12376a4798fd54d8a6719984e2fe8eR1131 or revert it?

**Comment by pennachin** [comment] 2017-04-19 17:22
@amebel it looks ok to me but I don't know anything about CMake functions. Do these changes preserve Linas' choices for where to install each module? 

I think the ocpkg change should be reverted (aside from the wordnet dependency).

**Comment by AmeBel** [comment] 2017-04-20 01:50
@pennachin Yes it preserves Linas's choice. `ADD_GUILE_MODULE` used to infer the installation path from the directory structure, now the destination path has to be explicitily specified. The only optional inference done now is to figure out which file specifies the module, as it's destination is different from the rest of the files. To do so it checks if the basename of the path passed by the keyword argument `MODULE_DESTINATION` is equal to the file name. 

In effect, it works similar to in-built `INSTALL`  command, with the addition of symlinking the files in the `build_directory/opencog/scm`. If you have issues with tests involving non-binding scheme modules or you made significant changes to the module structure you can `rm -rf build_direcory/opencog/scm ` and run cmake to create the symlinks.

**Comment by pennachin** [comment] 2017-04-20 13:56
Looks good to me, I recommend merging.

**Comment by linas** [comment] 2017-06-05 19:56
closing I think this is fixed

**Closed by linas** 2017-06-05 19:56 UTC
