### ISSUE TITLE
Missing links in R2L outputs

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#1912] opened 2015-12-01 07:49 UTC
After doing `(nlp-parse "Tom eats apples.")`, some of the outputs I got:
```
(ReferenceLink
   (InterpretationNode "sentence@98221381-38bf-4055-876a-70ff9d0ca3c6_parse_0_interpretation_$X")
   (SetLink
      (WordInstanceNode "Tom@20602354-4781-4ba5-bb95-e4f377a7b702")
      (WordInstanceNode "eats@3cecfd08-eac6-496e-affb-4f4d92b8e259")
      (WordInstanceNode "apples@6c172f9a-9ed6-420f-9c60-3381c22bd13b")
      (DefinedLinguisticConceptNode "present")
      (ConceptNode "Tom@20602354-4781-4ba5-bb95-e4f377a7b702")
      (ConceptNode "Tom")
      (DefinedLinguisticPredicateNode "definite")
      (ListLink
         (ConceptNode "Tom@20602354-4781-4ba5-bb95-e4f377a7b702")
      )
      (PredicateNode "eats@3cecfd08-eac6-496e-affb-4f4d92b8e259")
      (PredicateNode "eat")
      (ConceptNode "apples@6c172f9a-9ed6-420f-9c60-3381c22bd13b")
      (ConceptNode "apple")
      (ListLink
         (ConceptNode "Tom@20602354-4781-4ba5-bb95-e4f377a7b702")
         (ConceptNode "apples@6c172f9a-9ed6-420f-9c60-3381c22bd13b")
      )
   )
)
```
Looks like some InheritanceLink etc is missing. I guess it's because the "pre-xxx-rule" have been removed from some of the r2l rules, as a result a wrapper ListLink is not generated, so one of the `cog-delete-parent` in `r2l-parse` (https://github.com/opencog/opencog/blob/master/opencog/nlp/chatbot/chat-utils.scm#L58-L59) removed those InheritanceLink etc.

Anyway I think removing those "pre-xxx-rule" is good (I believe we don't really need them?), and I think we don't need that many ListLink to wrap the outputs generated by the rule either... so maybe one day we should get rid of all of them and remove a `cog-delete-parent` from `r2l-parse` to fix this problem.

**Comment by linas** [comment] 2015-12-01 17:29
OK. There was a different issue to: something was wrapping the AnchorNode in a SetLink, and thus, it was impossible to detect new sentences. This might actually be the root cause of the problem.

I don't understand why the SetLink is needed or is being used.  This is important: the only reason for those ugly UUID's is to create a network of links, so that you can always find what belongs to a given parse, simply by tracing the network of connections.   Thus, in principle, the SetLink isn't needed.

However, if we instead decide to encode all relations with a SetLink, then the UUID's are not needed.  Getting rid of the UUID's would simplify a lot of things.  We really should use one technique, or the other; not both.

**Comment by linas** [comment] 2015-12-01 17:39
In particular, if you want to remember a collection of sentences for a long time (i.e. for more than 5 or 10 seconds), it seems awfully wasteful to remember the UUID versions.  It would be better to just wrap up the non-UUID versions in a SetLink, and remember those...

**Comment by linas** [comment] 2015-12-01 17:45
Thinking aloud: the point of the UUID's was to allow the pattern matcher to walk over the network, but to limit it's search to just one given sentence.   Another way to achieve this would be to tell the pattern matcher to only explore the graph inside of some given SetLink, and never wander outside of it.  Currently, there is no way to tell it to do that, but it would not be hard to do.

This would allow us to partly get rid of the UUID's, I think, and simplify many of the R2L rules. It would be a big change, but maybe doable.  We still need some sort of mechanism to deal with two copies of the same word in one sentence.... Hmmm. easier said than done ...

**Comment by linas** [comment] 2015-12-01 18:08
Manhin, where is the SetLink created? I can't find it ...

**Comment by linas** [comment] 2015-12-01 18:28
OK, so I think I understand the issue:
1) The SetLink is being removed from the Atomspace, because it wraps the AnchorNode, which is bad. So one fix is to create the SetLink in such a way that it does not wrap the Anchor Node.   I cannot find the code that does this, so I can't fix it.

2) It seems that the output of all rules needs to be wrapped in a ListLink twice!? That seems weird, but that is fixable too.  However, I can't find the code that unwraps one of these two layers. Is it in the URE?  Does the URE need everything to be wrapped twice?

**Comment by linas** [comment] 2015-12-01 19:33
OK, so I attempted to fix both of these with pull request #1914 -- but it still doesn't work.

The ReferenceLink looks much better now:  `(cog-incoming-set (car (cog-get-atoms 'InterpretationNode)))` lists various InheritanceLnks.

**Comment by linas** [comment] 2015-12-01 19:59
I also found the spot where the wrapping ListLinks are removed: here: https://github.com/opencog/opencog/blob/master/opencog/nlp/chatbot/chat-utils.scm#L55-L60

 -- the `cog-delete-parent` is called three times in a row!! surely that is overkill and explains the double-wrapping of the ListLinks

**Comment by linas** [comment] 2015-12-01 22:08
Found the bug and fixed it.  It was ListLink madness.

**Comment by linas** [comment] 2015-12-01 22:38
Closing this works now.

**Closed** 2015-12-01 22:38 UTC

**Comment by linas** [comment] 2015-12-01 22:40
Oh, ths was the root cause of #1903 -- dulicate of #1903
