### ISSUE TITLE
Script to translate Relex2Logic rules into ImplicationLinks (enabling execution via Atomspace-based rule engine)

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1194] opened 2015-01-12 03:22 UTC
Currently the RelEx2Logic rules exist in a mixed format: there are “main rules” executed via a custom Java rule engine embedded in a RelEx output generator, assisted by “helper functions” written in Scheme and interacting directly with the Atomspace.

We would like to eliminate the use of the custom Java rule engine and have each RelEx2Logic rule executed via triggering an ImplicationLink (wrapped in a BindLink) in the AtomSpace. This involves wrapping the helper functions in GroundedSchemaNodes, and writing a script to map the main RelEx2Logic rules into ImplicationLinks among Atoms. In principle this is straightforward but various fixes and tweaks to various AtomSpace related functions will likely be required along the way.

**Comment by linas** [comment] 2015-01-12 05:57
duplicate of #1193

**Closed by linas** 2015-01-12 05:57 UTC
Labels: duplicate, enhancement, nlp
