### ISSUE TITLE
Move AttentionBank from AtomSpace to the AttentionModule

### ISSUE THREAD

**Issue by rTreutlein** [opencog/opencog#2333] opened 2016-07-30 09:24 UTC
The AttentionBank is currently part of the AtomSpace but it is only ever useful when you actually load the AttentionModule on the Cogserver. It would be cleaner if the AttentionBank would be part of the AttentionModule. This would also fix #2329.

The AtomSpace also contains various wrapper methods dealing with Attention that could be moved to the AttentionModule.

I can't think of any downsides to this, although it might break some code that I am not aware off.

What are your opinions on this?

**Comment by bgoertzel** [comment] 2016-07-30 17:16
Roman, conceptually the strategy you suggest seems appealing, though I haven't looked at that code closely enough to see if there are any severe hidden gotchas ...

**Comment by rTreutlein** [comment] 2016-07-30 17:23
Yea that's why I was asking. If nobody can think of anything ill just have to try it and see if any issues do come up.

**Comment by linas** [comment] 2016-07-31 00:22
@rTreutlein removing that would be an excellent idea. Its long been contemplated, for exactly the reasons you give -- it serves no purpose inside the atomspace. The actual removal has been a low priority, because mostly it doesn't interfere very much, and is mostly an annoyance.

So, yes, now that there is an obvious home for it, yes, please do remove it.

**Comment by linas** [comment] 2016-07-31 00:26
anyway, I expect no issues at all ...  Maybe the only subtlty to be aware of are the "temporary atomspaces" -- these get created and destroyed in rapid succession (millisecond timescale), when evaluating certain expressions. The attention mechanism should ignore these completely -- they are not only transient, but all atoms in them get deleted.  These transients are why there's a _zombie flag in the attention bank; that flag can now obviously be removed.

**Comment by linas** [comment] 2016-08-10 22:32
Ohh, this just got complicated and interesting -- see bug #2354.  Let me explain the issue in detail.

The atomspace/atomtable maintains a set of indexes, so that the lookup of atoms by name, type, etc. can be done quickly.  These indexes have to be updated every time an atom is added or deleted, and so, to make things thread-safe, a lock is taken when atoms are added/deleted to the atomspace. (The lock is also taken when using the indexes, so that readers don't get clobbered by writers)

One of the indexes is an "importance index", it sorts the atoms into fixed-width bins, depending on their STI.  This index is updated a LOT by the attention-allocation agents. This index uses the same lock as the rest of the atomspace, and so any heavy-duty updating of the AV values by the attention agents will slow down the atomspace a LOT for any/all other users.  This is the underlying bug for pull req #2354

The lock is here: https://github.com/opencog/atomspace/blob/master/opencog/atoms/base/Atom.cc#L196

This suggests that it is vitally important to also move the importanceIndex out from the AtomTable, and into the AttentionBank, and move the whole thing, per above.  The tricky part is to design it so that updating AV values frequently does not stall out or block the addition/removal of atoms to the atomspace.

**Comment by linas** [comment] 2016-08-10 22:46
The simplest solution I can think of, to prevent the problem of frequent AV changes from clobbering more mundane atomspace operations, is, when adding/removing an atom to the atomspace, to enqueue it in a queue, and then later (in a different thread, under a different lock) update the importanceIndex. 

Code to kind-of do that has already been mostly written, its here: https://github.com/opencog/atomspace/blob/master/opencog/atomspace/AtomTable.cc#L681-L689  however:
* it did not offer a perforamnce improvement
* it might fail some unit test(s), not sure (so its buggy)
* it shares the same lock with the rest of the atomtable so it does not solve the lock-contention problem -- it really should get its own lock.
* It handles the importanceIndex just like the other indexes; when clearly this index deserves its own lock.

Anyway, the point is that this kind of async-update solution needs to be moved to the attention bank for this particular index.

**Comment by linas** [comment] 2016-08-10 22:53
Suggested plan of action: move importance index to attention bank, first.  Emulate the async-update code, so that adding atoms to the attention bank does not interfere with the atomspace, per above.  Second step is to then move the whole attention bank to a new home.

**Comment by linas** [comment] 2016-08-11 20:20
Per @misgeatgit remark on #2354 --

The core issue is that the agents are causing a huge amount of lock contention -- they are monopolizing the lock on the atomspace, because _as->get_handle_set_in_attentional_focus takes a long time to run, and is called over and over. Pretty much no one else gets a chance to get in there and do anything.  http://stackoverflow.com/questions/1970345/what-is-thread-contention

The reason that the nano-sleep/thread_yeild works is because either of these calls descend to the Linux operating system kernel, and tell the process/thread scheduler that the current thread should be suspended, and that some other thread/process should be given a chance to run. The kernel then searches for runnable threads -- and finds one -- one of the other threads, that is waiting for the atomspace lock. Its scheduled, and it runs, and does it's stuff.

Without the nanosleep/yeild, that other thread almost never gets a chance to run: this thread is constantly releasing and grabbing the lock, and so, statistically, the chances are very small that the linux kernel scheduler will run, and find the lock not held. Thus, the other thread is "starved". https://en.wikipedia.org/wiki/Starvation_(computer_science)

**Comment by linas** [comment] 2016-08-11 20:23
There's also this, for background reading:
http://preshing.com/20111118/locks-arent-slow-lock-contention-is/
https://www.ibm.com/support/knowledgecenter/SS3KLZ/com.ibm.java.diagnostics.healthcenter.doc/topics/resolving.html
http://www.thinkingparallel.com/2007/07/31/10-ways-to-reduce-lock-contention-in-threaded-programs/
http://0pointer.de/blog/projects/mutrace.html

**Comment by linas** [comment] 2016-08-12 05:03
OK, so pull req opencog/atomspace#858 makes a cleaner separation of AttentionBank vs. AtomSpace.  Unfortunately, The `class Atom::setAV()` method(s) interact strongly with the AttentionBank, and it seems like somehow, this too should be refactored.  Not sure how, though.  Maybe AV should not be a part of the atom, at all, but should instead be stored only in the AttentionBank? ...This does make sense, in a way ...

**Comment by rTreutlein** [comment] 2016-08-12 05:50
I have been thinking about moving the AV away from the Atom as well. But how exactly would one accomplish this? Even using a HashMap to associate Atom -> AV seems inefficient. But if it can be done efficiently it is definitively worth considering.

**Comment by linas** [comment] 2016-08-12 16:27
Well, efficiency can be tricky business. If most atoms don't have an AV, then you can save some RAM by removing the AV from the atom. This might allow them to be packed more densly, fitting better into a cache, speeding computations.  Or maybe all atoms have an LTI, but very few have an STI?

Even if we do leave the AV pointer in the atom, it might be better to change the API so that you can only change an atoms AV by asking the bank to do it.  This would remove the use of the AVChhanged signal and maybe save some cpu cycles as a result. 

There's also a wilder idea, that remains incompletely developed ... its the idea of "protoatoms" -- The AV could be converted into a protoatom.  Now, protoatoms are kind-of-like regular atoms, except that they don't have a TV, AV or UUID. They are not stored in the atomspace, and they are not unique, in general.  They were invented with the idea that they would eventually replace the six different kinds of TV, and the (currently) one kind of AV, and, more generally, to associate arbitrary, generic attributes with an atom.   

They are not yet used, because we haven't yet quite nailed down the best way to use them -- there are several ways to deal with certain details (e.g. should there be a protolink? or should regular links be allowed to store protoatoms? and variants on this question - protoatoms are meant to store generic attributes for an atom - so whats the best way to find some given generic attirubte associated with an atom?)  So far, there has been no pressing need for them.   But perhaps it could be a path for AV.  It requires a bit more pondering, testing, decision-making.

**Comment by rTreutlein** [comment] 2016-08-12 17:40
Hm only a few Atoms having an STI could potentially be true for large AtomSpaces were only small portions are used at any given time but even then without some experimentation we can't know for sure.

Changing the API seems like a good option for now as it's relatively easy to implement. And would likely make further improvements or experiments easier to do.

I have looked at the protoatom code before. How exactly would you use it to store a value? Create a derived class that has a member variable containing the value? If the are only used to store attributes for an atom maybe the atom should contain a map/vector of protoatoms. That would seem the easiest way without the need for protolink. Not sure if you would lose some necessary flexibility with this, though.

**Comment by linas** [comment] 2016-08-12 18:49
>
>
> How exactly would you use it to store a value?
>
Not sure.


> Create a derived class that has a member variable containing the value?
>
Sure. Although, for most people, a vector of floats is enough.

> If the are only used to store attributes for an atom maybe the atom should
> contain a map/vector of protoatoms.
>
Which is what a protolink is.

> That would seem the easiest way without the need for protolink.
>
You suggest that all atoms should *be* protolinks.

> Not sure if you would lose some necessary flexibility with this, though.
>
The lost flexibility is that, if protoatoms don't behave (exactly) like
atoms, then  they need yet another, new API to access them. More API's mean
more complex code, tricker algorithms, more coding styles, some of which
are squirmy, because the programmer never quite bothered to think it
through, (because they were too lazy to figure out what protoatoms were or
how to use them effectively).

So, the goal/trick is to find some way of using them that fits naturally.
Not quite sure what that is.  Here's one idea:

   ProtoEvaluationLink
         PredicateNode "name of the attribute, e.g. AV"
         SomeAtom
         FloatValue   # which is a vector of floats holding the actual av

* where SomeAtom is the atom to be tagged with the attribute
* where the PredicateNode is an actual node, so that it's in the atomspace,
its globally unique, and thus easy to find.
* where the ProtoEvaluationLink shows up in the incoming set of both
SomeAtom, and of the PredicateNode, so that it is easy to find, given one
or the other or both.
* perhaps there should be a ProtoStateLink, which would be globally unique,
given the first two elements.
* Perhaps the ProtoStateLink should be a real actual link, kept in the
atomspace???

* What is the *fastest* algorithm for finding the value, given SomeAtom,
and the PredicateNode ... ? Perhaps the fastest algorithm would come from
using this structure:

   ProtoEvaluationLink
         ListLink      # a real link thus globally unique, and easily found
in the atomspace.
             PredicateNode "name of the attribute, e.g. AV"
             SomeAtom
         FloatValue   # which is a vector of floats holding the actual av

The above ListLink variant uses more RAM...

My current favorite ideas are the above or something very similar;  there
are certainly other ways to do things; do the other ways have an equally
simple API?

**Comment by linas** [comment] 2016-08-12 23:53
Created http://wiki.opencog.org/wikihome/index.php/ProtoAtom sith copy of above; See also opencog/atomspace#513 for a tracking bug for the ProtoAtom.

**Comment by rTreutlein** [comment] 2016-08-15 19:57
I now think using proton atoms is ultimately the best option.

I have been thinking about maybe turning the HebbianLinks into ProtoHebbianLinks. Right now only the AttentionSystem uses these Links and I don't see that changing in the future, also there could be 100 HebbianLinks for any 1 Atom in the system. Putting all those links in the AtomSpace seem like it would slow down the System unnecessarily. Moving them instead to the AttentionBank could improve performance.

Another issue this would fix is that the newest Hebbian Updating Algorithm requires tracking some additional variables for each link, which would be easy with a ProtoHebbianLink as we could just add another value to the FloatVector.

One more benefit is that HebbianLinks don't need to keep track of an AttentionValue with ProtoHebbianLinks we would get a nice reduction in MemorySize. Although if ProtoAtoms are used for TVs and AVs this would become a non-issue anyway.

Do I understand it correctly that this FloatVector would be part of any ProtoAtom or is that not decided yet?

**Comment by linas** [comment] 2016-08-15 20:41
You may want to re-read the comments above.

ProtoAtoms are a base class for Atoms and for Values.  As a base class, the ProtoAtom does NOT contain a TV, AV or any kind of floats or strings in it.

Atoms derive from ProtoAtoms and include TV and AV in them.

"Values" derive from ProtoAtoms and are containers for string or float-pt and/or other data values in them. 

The intent is that "Values"  can be used as "valuations" in classical logic -- wherever you might want to have a valuation for an atom, such as AV, TV, then, in the future, you would use some Value instead. https://en.wikipedia.org/wiki/Valuation_(logic)

The undecided bits all have to do with memory management. We use smart pointers, but exactly the same issues apply, if we used garbage collection instead.  The issue is that if a protoatom (atom or value) does not have a pointer to it, then it is deleted. This issue is solved for atoms with the atomspace: putting an atom into the atomspace guarantees that there is at least one pointer to it, and thus, it will not be deleted.

This issue is NOT solved for values, in general. There are several ways to solve this issue, but each seems to have some serious negative consequences.  One way, partly implemented in the code, is to have atoms point at their values. This leads to a large number of nasty software and design issues, so I think it just won't work.

My current favorite for this would be to allow users to create "ValueSpaces".  They would be kind-of-like AtomSpaces, except that they'd hold values.  For example, given some valuespace X, and some atom A, you could ask for the value of X at A.  The implementation would use C++ std::map or std::unordered_map to create a lookup table pairing atoms A to their values.

An example of X might be some future version of the AttentionBank, given an Atom A, you ask it, and it will tell you what the associated AV is.

Recall the discussion above, where I said this:
```
   ProtoEvaluationLink
         PredicateNode "name of the attribute, e.g. AV"
         SomeAtom
         FloatValue   # which is a vector of floats holding the actual av
```

The above is in fact deeply flawed -- if nothing points at this ProtoEvaluationLink, the smart pointers will make it go "poof"  somebody, somewhere, has to hold on to a pointer to it. (again, if we used garbage collection instead of smart pointers, we'd still have exactly the same problem).  There are multple solutions:

Solution A) Do NOT use a `ProtoEvaluationLink` and instead use a real atom, a `ValuationLink` and poke the ValuationLink into the atomspace. This is yucky for several reasons, which you may ponder.

Solution B) Do use a  `ProtoEvaluationLink` and place it into a PELSpace, whose only job is to hold such things.

Solution C) Do NOT use a  `ProtoEvaluationLink`, and instead, create a ValuationSpace that uses C++ std::map ti link `SomeAtom` with `FloatValue`.

Solution C seems like the cleanest for some future AttentionBank.

Each of these solutions have distinct implications for the scheme and python API's, and, more seriously, for the REST API and most importantly for the database (save-to-disk) and distributed (cloud) operation.  The trade-offs are annoying to think about, as each seems to have strong positives and strong negaives

**Comment by rTreutlein** [comment] 2016-08-15 20:53
Found the Issue in my thought process. I thought that the Atom would point
to the ProtoLink via the IncomingSet but it's only a weak Pointer.

And you can't have shared pointers there because then you get cycles.
Okay, I think I get the problem now.

**Comment by linas** [comment] 2016-12-29 00:03
OK, so pull reqs #1050 and #1051 accomplish much of the work described and desired above. The remaining work is to move the AV out from the atoms. This seems like the right thing to do, because, currently, that AV setter and getter are directly tangled into the AttentionBank, and use this crazy convoluted message-passing scheme to talk to one-another.  It would be simpler to just have  the AttentionBank mange this directly.

**Comment by linas** [comment] 2016-12-29 21:47
I believe that pull reqs opencog/atomspace#1052 and #2560 complete the process of cleanly dettaching the attentionbank from the atomsapce. FWIW, atoms are now smaller, and the atomspace benchmarks run 25% faster than they did last week, adding to gains obtained from removing UUID's. Compared to a year ago, addNode is twice as fast, addLink is not quite 2x faster, removeAtom is almost 3x faster.

I'm closing this; if there are other issues, open new bug reports.

**Closed by linas** 2016-12-29 21:47 UTC
Labels: attention-allocation, state:bug, state:enhancement
