### ISSUE TITLE
Fatal error (OpenCog crash) remove_atom not implemented with backing_store when using the microplanning

### ISSUE THREAD

**Issue by SamuelHassine** [opencog/opencog#1721] opened 2015-08-14 08:12 UTC
Hello,

I would like to use the Microplanning with Sureal in order to start a language generation pipeline.

Sureal is working but Microplanning makes OpenCog server crashing.

Steps to reproduce:

1. Start OpenCog Server
2. Start Relex server with --relex --link --logic
3. Load data:

``` bash
guile> (load "../opencog/nlp/microplanning/main.scm")
guile> (load "../tests/nlp/microplanning/test-atomspace.scm")
(InheritanceLink (stv 0.99000001 0.99000001)
   (ConceptNode "pine@981c495c-1111-4bb2-8f7f-164a1122cae6" (stv 0.001 0.99000001))
   (ConceptNode "tree@160bc480-942c-4421-b798-04c004c011f5" (stv 0.001 0.99000001))
)
guile> (microplanning test-declarative-sal "declarative")
Connection closed by foreign host.
```

The error log:
```
2015-08-14_08:07:46.82474 [2015-08-14 08:07:46:678] [ERROR] Not implemented!!! (/usr/local/src/atomspace/opencog/atomspace/AtomSpace.cc:350)
2015-08-14_08:07:46.82487       Stack Trace:
2015-08-14_08:07:46.82491       2: basic_string.h:293     std::string::_M_data() const
2015-08-14_08:07:46.82495       3: Logger.cc:463          opencog::Logger::Error::operator()(char const*, ...)
2015-08-14_08:07:46.82500       4: exceptions.cc:52       opencog::StandardException::parseErrorMessage(char const*, __va_list_tag*, bool)
2015-08-14_08:07:46.82505       5: exceptions.cc:69       opencog::StandardException::parseErrorMessage(char const*, char const*, __va_list_tag*, bool)
2015-08-14_08:07:46.82543       6: exceptions.cc:137      opencog::RuntimeException::RuntimeException(char const*, char const*, ...)
2015-08-14_08:07:46.82544       7: AtomSpace.cc:350       opencog::AtomSpace::remove_atom(opencog::Handle, bool)
2015-08-14_08:07:46.82545       8: shared_ptr_base.h:545        ~__shared_count()
2015-08-14_08:07:46.82546       9: ??:0 scm_vm_engine()
2015-08-14_08:07:46.82546       10: ??:0        scm_call_1()
2015-08-14_08:07:46.82547       11: ??:0        scm_vm_engine()
2015-08-14_08:07:46.82547       12: ??:0        scm_call_3()
2015-08-14_08:07:46.82548       13: ??:0        scm_vm_engine()
2015-08-14_08:07:46.82548       14: ??:0        scm_call_4()
2015-08-14_08:07:46.82548       15: SchemeEval.cc:612     opencog::SchemeEval::do_eval(std::string const&)
2015-08-14_08:07:46.82549       16: SchemeEval.cc:541     opencog::SchemeEval::c_wrap_eval(void*)
2015-08-14_08:07:46.82549       17: ??:0        scm_at_abort()
2015-08-14_08:07:46.82550       18: ??:0        scm_vm_engine()
2015-08-14_08:07:46.82551       19: ??:0        scm_call_4()
2015-08-14_08:07:46.82551       20: ??:0        scm_at_abort()
2015-08-14_08:07:46.82552       21: ??:0        scm_c_with_continuation_barrier()
2015-08-14_08:07:46.82552       22: ??:0        GC_call_with_gc_active()
2015-08-14_08:07:46.82552       23: ??:0        scm_current_processor_count()
2015-08-14_08:07:46.82554       24: ??:0        GC_call_with_stack_base()
2015-08-14_08:07:46.82555       25: ??:0        scm_with_guile()
2015-08-14_08:07:46.82556       26: SchemeEval.cc:508     opencog::SchemeEval::eval_expr(std::string const&)
2015-08-14_08:07:46.82557       27: basic_string.h:293    std::string::_M_data() const
2015-08-14_08:07:46.82558       28: ??:0          std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)
2015-08-14_08:07:46.82559       29: pthread_create.c:312        start_thread()
2015-08-14_08:07:46.82560       30: clone.S:113 clone()
2015-08-14_08:07:46.82561
2015-08-14_08:07:46.82614 terminate called after throwing an instance of 'opencog::RuntimeException'
2015-08-14_08:07:46.82620   what():  Not implemented!!! (/usr/local/src/atomspace/opencog/atomspace/AtomSpace.cc:350)
2015-08-14_08:07:46.98939 [2015-08-14 08:07:46:826] [ERROR] Caught signal 6 (Aborted) on thread 140231613343488
2015-08-14_08:07:46.98952       Stack Trace:
2015-08-14_08:07:46.98957       2: basic_string.h:539   ~basic_string()
2015-08-14_08:07:46.98961       3: CogServerMain.cc:79  _Z7sighandi()
2015-08-14_08:07:46.98966       4: ??:0 killpg()
2015-08-14_08:07:46.98989       5: raise.c:56   __GI_raise()
2015-08-14_08:07:46.98990       6: abort.c:91   __GI_abort()
2015-08-14_08:07:46.98991       7: ??:0   __gnu_cxx::__verbose_terminate_handler()
2015-08-14_08:07:46.98991       8: ??:0 _ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE()
2015-08-14_08:07:46.98992       9: ??:0 _ZSt9terminatev()
2015-08-14_08:07:46.98993       10: ??:0          std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)
2015-08-14_08:07:46.98993       11: pthread_create.c:312        start_thread()
2015-08-14_08:07:46.98994       12: clone.S:113 clone()
2015-08-14_08:07:46.98994
```

**Comment by williampma** [comment] 2015-08-14 08:27
humm... couldn't reproduce...

```
guile> (load "../opencog/nlp/microplanning/main.scm")

guile> (load "../tests/nlp/microplanning/test-atomspace.scm")
(InheritanceLink (stv 0.99000001 0.99000001)
   (ConceptNode "pine@981c495c-1111-4bb2-8f7f-164a1122cae6" (stv 0.001 0.99000001))
   (ConceptNode "tree@160bc480-942c-4421-b798-04c004c011f5" (stv 0.001 0.99000001))
)

guile> (microplanning test-declarative-sal "declarative")
#f
guile> 

```

**Comment by williampma** [comment] 2015-08-14 08:30
Ah, because of the `backing_store` check, and I don't have any installed.

Apparently `backing_store` has not implemented `remove_atom`

**Comment by williampma** [comment] 2015-08-14 08:31
See https://github.com/opencog/atomspace/blob/master/opencog/atomspace/AtomSpace.cc#L346-L351

**Comment by linas** [comment] 2015-08-14 22:49
William,

I'm pretty sure that microplanniing should not be calling remove-atom,
anyway, it should probably be calling purge-atom (which deletes it from the
atomspace, but not the backing store, thus avoiding that assert, even if
backing store is turned on).

-- Linas

**Comment by linas** [comment] 2015-09-01 20:04
Closing this issue; the core implmentation work is to be tracked with https://github.com/opencog/atomspace/issues/255

**Closed by linas** 2015-09-01 20:04 UTC

**Comment by linas** [comment] 2017-08-17 16:17
FYI feature enhancement #255 now finished.
