### ISSUE TITLE
Anonymous vs defined predicates

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1432] opened 2015-03-18 08:30 UTC
Related to the hijacking discussion from issue #1424, besides anonymous definitions (what the LambdaLink offers) maybe we could add a named definition? That might be what we want most of the time and is slightly more compact. Consider the following hypothetical DefinePredicateLink:
```
DefinePredicateLink
    PredicateNode: <predicate_name>    
    <arguments>
    <body>
```
instead of saying
```
EquivalenceLink
    PredicateNode <predicate_name>
    LambdaLink
        <arguments>
        <body>
```

That way we get terseness without introducing ambiguities.

**Comment by AmeBel** [comment] 2015-03-19 00:53
would you please elaborate on the EquivalenceLink above? What does it mean?

**Comment by AmeBel** [comment] 2015-03-19 03:13
treating BindLink as a lambda i see the similarity.

**Comment by linas** [comment] 2015-03-19 04:26
I see the idea, but am unclear on the semantics. Originally, BindLink was intentionally designed to look exactly like a LambdaLink (I wanted to leave the LambdaLink name open, so that we could define it nicely in the future, once we understood what we're doing),   Next -- BindLink was designed specifically to be used for the pattern-matcher, and not other things.

So, DefinePredicateLink looks nice and all, but .. what are we supposed to do with it?  When is it evaluated, or grounded? When would we use it, and for what?

Other questions: What should happen when the pattern matcher stumbles across nested BingLinks (or nested DefinedPredicteLink's)? Should it perform a grounding on the sub-pattern, first? I guess it should ... 

Note: if we want the pattern matcher to automatically ground any sub-patterns the it finds (i.e. the nested DefinedPredicateLinks), then the pattern matcher starts looking more and more like Prolog, or like ASP (answer-set programming, which uses the Prolog syntax, and a modified evaluator).   The pattern matcher already looks like ASP -- 

Note: for ASP, one writes down arbitrarily complicated boolean expressions, and the ASP solver finds "groundings", assigning each variable a T or F in such a way that all of the boolean expressions are consistent. Prolog does this too, except Prolog stops after it finds the first solution; ASP can find all solutions. So PM is sort-of-like ASP, except that PM grounds variables with atoms, not with T,F.

We can add DefinedPredicateLinks, but lets be clear: this does not make the atomspace look more lisp-like nor does it look more Haskell-like. The basic concept of Haskell is still "evaluation", whereas the basic concept of the PM is "grounding".

Lets see .. and there there's Kripke frames ...

**Comment by ngeiswei** [comment] 2015-03-19 11:05
The only purpose is to save BindLinks from cluttering the AtomSpace while avoiding potential ambiguities of implicit BindLinks. The Haskell equivalent would be using

```
f x y z = <body containing x y z>
```

rather than

```
f = \ x y z -> <body containing x y z>
```

As to whether it should be evaluated of grounded, I don't really know, I guess if it's not quoted it should be evaluated.

**Comment by linas** [comment] 2015-03-20 00:31
oh, well, as a general rule, I dislike adding things unless there is a clear need for it.  Otherwise, one ends up with a clutter of code that no one uses,, a clutter of documentation that no one understands, and a difficult time of changing it or fixing it removing it, because you are afraid of breaking something important.

So, having a DefinedPredicate sounds plausible and interesting, .. but it needs some sort of semantics.

**Comment by ngeiswei** [comment] 2015-03-20 07:41
I agree about not adding things unless there are really necessary. I'm just trying to provide alternative options to avoid cluttering the AtomSpace with BindLinks/LambdaLinks. Although ultimately I don't mind having BindLinks/LambdaLink since I think they are really necessary.

**Comment by linas** [comment] 2015-03-26 02:08
A DefineLink (not a DefinePredicateLink) would be useful or needed for implementing recursion in the pattern matcher, see issue #1458. Recursion is the "last missing piece" that would make the pattern matcher into a generic prolog-like or answer-set-like programming environment.

**Comment by linas** [comment] 2015-08-31 16:51
Closing, I beleive that this is fully resolved in 
https://github.com/opencog/atomspace/issues/74

We now have a fully-implemented LambdaLink, and a semi-working DefineLink in the code.

**Closed by linas** 2015-08-31 16:51 UTC
Labels: pln, state:enhancement
