### ISSUE TITLE
Walkaround for : In procedure cog-bind: Not implemented!!! when running chatbot. ( add to chatbot's readme ? ) 

### ISSUE THREAD

**Issue by phion140** [opencog/opencog#2019] opened 2016-02-05 20:37 UTC
While trying to run the chatbot, i had this error, it so happens that cog-bind and cog-fc use Remove_atom () which is not implemented.
So i had  to call for purge_atom inside of remove_atom : 

bool AtomSpace::remove_atom(Handle h, bool recursive)
{
    if (backing_store) {
        purge_atom(h,recursive);
    }
    return 0 < atomTable.extract(h, recursive).size();
}
Hope it helps .

**Comment by linas** [comment] 2016-02-22 21:42
Closing, this is a duplicate of opencog/atomspace#255

**Closed by linas** 2016-02-22 21:42 UTC
