### ISSUE TITLE
Integration with game character control

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1205] opened 2015-01-12 04:06 UTC
Tweaking the various speech act schema and associated hard-coded dialogue rules for appropriateness in the game context.

Subtle issues here would seem to be:
- Goals specific to the game world context, and their connection with speech acts
- Articulation of descriptions of things in the game world environment
- Articulation of events, processes and sequences in the game world

**Comment by linas** [comment] 2015-01-12 05:59
This is almost a duplicate of #1204 ...

**Comment by linas** [comment] 2016-06-29 00:59
closing as duplicate of #1204

**Closed by linas** 2016-06-29 00:59 UTC
Labels: embodiment, nlp, state:enhancement
