### ISSUE TITLE
wont compile with HAVE_SQL_STORAGE?

### ISSUE THREAD

**Issue by tigros** [opencog/opencog#1639] opened 2015-06-08 02:17 UTC
Hi,

I've been trying to get Unity3DGameWorldPlayer to work but having some difficulty. Not sure if anyone from outside got it to work yet? Seems to be some missing parts. It compiles, runs and connects but robot doesn't move, just disappears after couple minutes, I think missing processes.

While troubleshooting decided to try and get rid of the "No database persistant storage configured" and "Server compiled without database support" messages seen in logs. It's pretty much the only error left. 

So I defined HAVE_SQL_STORAGE where I believe needed and created the postgre database, recompiled atomspace ok but opencog compile produces this error:

...
[ 25%] Built target PythonModule
[ 25%] Built target atomspacepublishermodule
[ 28%] Built target builtinreqs
Linking CXX executable cogserver
libserver.so: undefined reference to `typeinfo for opencog::PersistModule'

libserver.so: undefined reference to `opencog::PersistModule::do_open(opencog::Request*, std::list<std::string, std::allocator<std::string> >)'
collect2: error: ld returned 1 exit status
opencog/server/CMakeFiles/cogserver.dir/build.make:118: recipe for target 'opencog/server/cogserver' failed
make[2]: *** [opencog/server/cogserver] Error 1
CMakeFiles/Makefile2:1569: recipe for target 'opencog/server/CMakeFiles/cogserver.dir/all' failed
make[1]: *** [opencog/server/CMakeFiles/cogserver.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

The code involved is in CogServer.cc:

    // Do this all very politely, by loading the required module,
    // and then calling methods on it, as needed.
    loadModule("libPersistModule.so");

    Module *mod = getModule("opencog::PersistModule");
    if (NULL == mod)
    {
        logger().warn("Failed to pre-load database, because persist module not found!\n");
        return;
    }
    PersistModule *pm = dynamic_cast<PersistModule *>(mod);
    const std::string &resp = pm->do_open(NULL, args);
    
    
I've searched the net far and wide, tried changing CMakeLists.txt of both atomspace and opencog to have some options like SET(CMAKE_C_FLAGS "-frtti -Wl,-E -Wl,-ldl -Wall -fPIC"), none got rid of error, I could be way off, I'm more of a Windows programmer, but this is all quite interesting and learning lots on the way. I couldn't spot any problems with the code like the DECLARE_CMD_REQUEST macro according to my internet searches.

Has anyone seen this or have a track to follow?

Thanks a bunch!

PS This is Ubuntu 14.10 in VMware Win7 host.

**Comment by linas** [comment] 2015-06-08 05:44
you should not define HAVE_SQL_STORAGE by hand -- it would be set for you automatically, if you have the unixodbc-dev package installed.

The error message `undefined reference to `opencog::PersistModule::do_open(` susuggests that  somehow there maybe is a libPersistModule.so but perhaps its empty .... 

I believe that installing unixodbc-dev should be enough. ... but be sure to rebuild the atomspace, including the cmake step, as otherwise, cmake remembers from last time that it did not find it. 

FWIW -- I am sure that the Unity3D does not make use of SQL, at all. Last post on Unity3D that I saw was frustration that the unity code was all a squirrly spaghetti code and was not worth fixing. So I'm guessing that would explain 100% of your unity symptoms ...

**Comment by tigros** [comment] 2015-06-08 06:55
Thanks, yes I was pretty sure it didn't use SQL, but went ahead just for fun and ended up with this difficult to fix linker error. Already had unixodbc-dev installed, atomspace asks for database pwd on cmake, all that works, but if I don't define HAVE_SQL_STORAGE myself it is not happening automatically with opencog, just atomspace where I see it in the flags.make files etc.

Here's the output of cmake on atomspace:

admin2@ubuntu:~/atomspace/build$ cmake ..
-- Build type: Release
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105500 found.
-- Found CogUtil version 2.0.1 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- GHC was found.
-- GSL found.
-- Guile (2.0.11 >= 2.0.0) was found.
-- HyperTable was not found. Make sure HYPERTABLE_LIBRARY and HYPERTABLE_INCLUDE_DIR are set.
-- Hypertable not found; the experimental distributed persistence DB needs it.
-- Python libs found.
-- Cython ( 0.20.2 >= 0.19.0) found.
-- Python destination dir found: /usr/lib/python2.7/dist-packages
-- Found Intel TBB
-- 
-- UnixODBC was found.
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- VALGRIND missing: needed for thread debugging.
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Detected ZeroMQ version number: 4.0.4
-- ZeroMQ was found.
Password for user opencog_tester: 
-- Postgres database is configured for unit tests.

The following components will be built:
-----------------------------------------------
   AtomSpace        - A weighted and typed hypergraph database.
   Cython bindings  - Cython (python) bindings.
   Doxygen          - Code documentation.
   Python tests     - Python bindings nose tests.
   Scheme bindings  - Scheme bindings and shell.
   SQL persistance  - Save/Restore of AtomSpace to database.
   TBB              - Intel TBB (Threaded Building Blocks) for multithreading.
   Unit tests       - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   Hypertable       - HyperTable for scalable persistance (experimental).

-- Configuring done
-- Generating done
-- Build files have been written to: /home/admin2/atomspace/build

You can see postgre is setup properly otherwise it would complain after entering password for user opencog_tester. So something missing somewhere as far as HAVE_SQL_STORAGE is concerned on the opencog side.

The output of opencog cmake is:

admin2@ubuntu:~/opencog/build$ cmake ..
-- Build type: Release
-- Found CogUtil version 2.0.1 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- Found AtomSpaced at /usr/local/lib/opencog/libatomspace.so
-- AtomSpace found.
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105500 found.
-- Found Boost::program_options
-- Found Boost::math
-- GHC was found.
-- Could NOT find GTK3 (missing:  GTK3_LIBRARIES GTK3_INCLUDE_DIRS) 
-- GTK missing: needed for the the gtk-visualizer.
-- Guile (2.0.11 >= 2.0.0) was found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- link-grammar( >= 4.7.12) was not found. Make sure LINK_GRAMMAR_LIBRARY, LINK_GRAMMAR_INCLUDE_DIR and LINK_GRAMMAR_DATA_DIR are set.
-- Link Grammar missing: needed for the Viterbi parser.
-- Found MOSES library: /usr/local/lib/libmoses.so
-- MOSES was found.
-- OpenGL was found.
-- Found these protobuf libs: /usr/local/lib/libprotobuf.so
-- Protobuf was found.
-- Python libs found.
-- Cython ( 0.20.2 >= 0.19.0) found.
-- Python destination dir found: /usr/lib/python2.7/dist-packages
-- SDL was found.
-- SDL_gfx was found
-- Found Intel TBB
-- 
-- Could NOT find TCLTK (missing:  TK_INCLUDE_PATH) 
-- Could NOT find TK (missing:  TK_INCLUDE_PATH) 
-- TCL shell was found here: /usr/bin/tclsh
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- VALGRIND missing: needed for thread debugging.
-- Found Xerces 3.1.1 -- /usr/lib/x86_64-linux-gnu/libxerces-c.so
-- Found ZeroMQ library: /usr/lib/x86_64-linux-gnu/libzmq.so
-- Detected ZeroMQ version number: 4.0.4
-- ZeroMQ was found.


The following components will be built:
-----------------------------------------------
   Attention        - Agents for attention allocation dynamics.
   Blopex           - BLOPEX block eigenvalue solver.
   Cython bindings  - Cython (python) bindings.
   Dim. Embedding   - Compute dimensional embedding of the AtomSpace.
   Doxygen          - Code documentation.
   Embodiment       - Architecture for embodiment.
   Learning Server  - Embodiment Learning.
   Python tests     - Python bindings nose tests.
   Server           - The CogServer.
   Spatial          - Vizualisation of the 3D spacemap.
   TBB              - Intel TBB for multithreading.
   Ubigraph         - Visualisation of the AtomSpace.
   Unit tests       - Unit tests.
   ZMQ              - ZMQ-based OAC GUI reports, AtomSpace publisher module.

The following components WILL NOT be built:
-----------------------------------------------
   GTK Visualizer   - GTK3-based Atomspace Visualizer.
   Viterbi          - Viterbi Parser for Link Grammar.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/admin2/opencog/build

Where there's no mention of SQL persistance. The curious thing is really the libserver.so: undefined reference to `typeinfo for opencog::PersistModule error, can't figure out how to fix even though tried a few solutions I found on the net like adding like -frtti and -Wl,-E compiler options, some subtle *nix thing it seems.

Anyway tried removing my HAVE_SQL_STORAGE defines, it compiles but no SQL support.

Thanks

**Comment by tigros** [comment] 2015-06-08 07:42
I just noticed the libPersistModule.so's I have are from June 2, so maybe it's not built early enough in the make to link with libserver.so? I mean when HAVE_SQL_STORAGE is set manually.

**Comment by linas** [comment] 2015-06-08 15:40
Punt on this, for now. so, libPersistModule.so does get built .. the #if HAVE_SQL_SERVR code in cogserver does not get built, but it you specify libPersistModule.so in your cogserver.conf file, it will get loaded, and SQL will work fine.  

I'm not sure why the cogserver thought it needed to load this module itself.

**Comment by tigros** [comment] 2015-06-08 18:43
In CogServerMain.cc in the main() function there's

    // Open database *before* loading modules, since the modules
    // might create atoms, and we can't have that happen until 
    // storage is open, as otherwise, there will be handle conflicts.
    cogserve.openDatabase();

so the comments might explain why a little. It's called in a couple other places too like CogServerSCM.cc and OACExecutable.cc. Sure appears like it needs to compile with HAVE_SQL_STORAGE.

It's the only place in the whole code where dlopen is used so can't compare notes, I don't get why typeinfo for opencog::PersistModule isn't beeing emmitted, or w/e the problem is. Do you have any idea why?

**Comment by linas** [comment] 2015-06-09 02:03
no idea why, you don't need it for unity, you don't need it for any other functional subsystem.

**Comment by tigros** [comment] 2015-06-09 02:34
just took a nap and dreamt about this, it said to put a -h compiler switch lol guess i'm no Edgar Cayce lol

Thanks anyway!

**Comment by tigros** [comment] 2015-06-09 18:03
fyi changed #include <opencog/modules/PersistModule.h> to #include <opencog/modules/PersistModule.cc> CogServer.cc now compiles. wow after all that it took 3 keystrokes, go figure!  Of course it can still be wrong tho, still having db connect issues in logs, but that could be just config problem, not sure yet.

**Comment by tigros** [comment] 2015-06-09 19:27
haha the dream i had, said put -h, it also said -h means -header-files woohoo I AM EDGAR! ha!

**Comment by tigros** [comment] 2015-06-10 08:15
The connect problem turned out to be a mismatch between /etc/odbcinst.ini and ~/.odbc.ini, needed Driver = PostgreSQL Unicode in odbc.ini

**Comment by linas** [comment] 2015-07-19 17:18
fwiw, I removed the HAVE_SQL test entirely; that test is done in the atomspace, and not here; here it should be unconditional. I pushed this out in some very recent pull request...

**Comment by linas** [comment] 2015-07-19 17:19
am closing, because I think the issue is fixed.. open a new bug if not

**Closed by linas** 2015-07-19 17:18 UTC

**Comment by linas** [comment] 2015-07-19 17:20
it was pull request 1687
