### ISSUE TITLE
404 link to tutorial

### ISSUE THREAD

**Issue by jurjendevries** [opencog/opencog#2552] opened 2016-12-27 15:26 UTC
In the README.md file there is a link to 'An interactive tutorial for getting started is available at: https://github.com/opencog/opencog/blob/master/TUTORIAL.md  ' . This gives me a 404 error.

**Comment by linas** [comment] 2016-12-27 18:59
I just now re-wrote the README, and removed that sentence.  See pull req #2553

**Comment by linas** [comment] 2016-12-27 19:03
I also added an overview, and also this paragraph, which is probably relevant:

There is no single "demo" or system that can be "run"; rather, the
various subsystems can be run individually, or together. The single
most-fully-integrated, complete demo would be the embodied [Hanson
Robotics](http://github.com/hansonrobotics) chat subsystem.  This
can be run *without* having an actual robot; a virtual Blender
animation may be used instead; a webcam and microphones are required
for sensory input. Portions of this system can be found in the `nlp`
directory, in this repo, as well as the
[ROS Behavior Scripting](https://github.com/opencog/ros-behavior-scripting)
repo. The full setup is located in the Hanson Robotics
[HEAD](https://github.com/hansonrobotics/HEAD) repo, and ready-to-run
Docker images can be found in the [OpenCog Docker
repo](https://github.com/opencog/docker).

**Comment by linas** [comment] 2017-01-02 19:46
closing cause I think the issue is fixed, right?

**Closed by linas** 2017-01-02 19:46 UTC
