### ISSUE TITLE
OpenCog pattern miner not working

### ISSUE THREAD

**Issue by tanksha** [opencog/opencog#2477] opened 2016-11-14 13:38 UTC
Hello,
I am using OpenCog pattern miner for the attached scheme files loaded to the AtomSpace, and it is not working.

**STEPS I followed**

1. Start opencog server with the config file  `-c ../lib/opencog_patternminer.conf` and relex server

2. Telnet to opencog server on port 17001 and access the scheme shell

3. `(use-modules (opencog) (opencog nlp) (opencog nlp chatbot) (opencog nlp relex2logic))`

4. `(clear)` to remove the VariableNode instances created by nlp and relex2logic modules (OpencCog pattern miner encounters an error finding VariableNode in the atomspace)

6. `(load-scm-from-file "test-dialogue.scm")`
    `(load-scm-from-file "back-ground.scm")`

7. Exit the scheme shell and load the test pattern miner agent module
   `loadmodule <OPENCOG_REPO>/build/opencog/learning/PatternMiner/libTestPatternMinerAgent.so`

8. From the opencog server I got this
```
Listening on port 17001
Debug: PatternMining start! Max gram = 4, mode = Depth_First
Start thread 0 from 0 to 4765
0% completed in Thread 0.
```
It stays like this ... waited long but nothing happened

**another example without the use of relex server**
1. Start and connect to OpenCog server (using `../lib/opencog_patternminer.conf`)

2. `(use-modules (opencog) (opencog nlp))`

3. `(load-scm-from-file "test-dialogue2.scm")`
    `(load-scm-from-file "back-ground.scm")`
As you see from the attached files `test-dialogue2.scm` doesn’t call for `(nlp-parse)` rather each words of a sentence are listed as a WordNode and the InheritanceLink is created to the user which the sentence belongs. 

4. Exit the scheme shell and load the test pattern miner agent module
   `loadmodule <OPENCOG_REPO>/build/opencog/learning/PatternMiner/libTestPatternMinerAgent.so`

in this case the pattern miner starts mining and stops at some percent , here is the screen copy
```
Listening on port 17001
Debug: PatternMining start! Max gram = 4, mode = Depth_First
Start thread 0 from 0 to 119
51.6667% completed in Thread 0.
```

[dialogue-example.tar.gz](https://github.com/opencog/opencog/files/589429/dialogue-example.tar.gz)

**Comment by ngeiswei** [comment] 2016-11-15 18:11
@tanksha I can't reproduce. Here's what I have done (version without relex)

1. copy `test-dialogue2.scm` and `back-ground.scm` under `<OPENCOG_REPO>/build/opencog/cogserver/server`

2. run the cogserver from the same directory with command line `./cogserver -c ../../../../lib/opencog_patternminer.conf`

3. run telnet from the same directory

4. in the telnet, load the modules, then load `test-dialogue2.scm` and `back-ground.scm`. I tried to load using `load` or `load-scm-from-file`, doesn't do anything either way. `load-scm-from-file` returns 0, while `load` returns
```
(InheritanceLink
   (ConceptNode "")
   (ListLink
   )
)
```
and
```
(load "back-ground.scm")
(InheritanceLink (stv 1 1)
   (ConceptNode "brainless")
   (ConceptNode "negative")
)
```
for `(load "test-dialogue2.scm")` and `(load "back-ground.scm")` respectively.

Any idea what I'm doing wrong?

**Comment by linas** [comment] 2016-11-15 18:15
load generally returns the last thing in the file. You can suppress that by puttingthe string `*unspecified*` at the end.

**Comment by linas** [comment] 2016-11-15 18:18
The print out `Start thread 0 from 0 to 4765` sure looks bad. If that is really the case, that is the core bug: certainly, Linux can run five thousand threads, but it will take much more than an hour-and-a-half wall-clock time for one thread to get one cpu-second of time.

**Comment by ngeiswei** [comment] 2016-11-16 06:41
I had forgotten to install cpprest. Unfortunately I still cannot run it. However the PatternMinerUTest on https://github.com/ngeiswei/opencog/tree/hack-pattern-miner runs (and fails) so I'll start from that.

**Comment by tanksha** [comment] 2016-11-16 08:53
@ngeiswei ... Here is what I did in detail
I copied test-dialogue2.scm and back-ground.scm under <OPENCOG_REPO>/build/
and 
- Start OpenCog server with under the same directory 
          ./opencog/cogserver/server/cogserver -c ../lib/opencog_patternminer.conf
- Telnet to 17001 and 
Connected to localhost.
Escape character is '^]'.
opencog> scm
Entering scheme shell; use ^D or a single . on a line by itself to exit.
guile> (use-modules (opencog) (opencog nlp))
guile> (load-scm-from-file "test-dialogue2.scm")
0
guile> (load-scm-from-file "back-ground.scm")
0
guile> (count-all)
396
guile> .
Exiting the shell
opencog> loadmodule /home/tanksha/opencog_ws/opencog/build/opencog/learning/PatternMiner/libTestPatternMinerAgent.so
done
opencog> 

- In the cogserver shell I found this, and it stacks. the percent doesn’t increase. But everytime i run it, it stacks in different percent number. Last time it reachs 51% and today it reaches 45% and stop. 

Listening on port 17001
Debug: PatternMining start! Max gram = 4, mode = Depth_First
Start thread 0 from 0 to 119
45.8333% completed in Thread 0..

**Comment by ngeiswei** [comment] 2016-11-16 09:02
Ah, OK, I didn't load the module, now I'm getting something similar.

**Comment by ngeiswei** [comment] 2016-11-16 09:32
It freezes here https://github.com/opencog/opencog/blob/master/opencog/learning/PatternMiner/PatternMinerDF.cc#L188 looking at the increasing timing between each loop it's probably a case of combinatorial explosion.

**Comment by ngeiswei** [comment] 2016-11-16 09:36
So I don't have any easy suggestion to offer. We have to bite the bullet and review it carefully, understand what it's doing, clean the code and fix it.

I'm gonna merge my branch so far, there isn't much except a unit test that needs to be completed, My plan was to disentangling TestPatternMinerAgent from the pattern code and move in this unit test, so you could start there.

**Comment by bgoertzel** [comment] 2016-11-16 10:10
Hmm, so maybe some special case filter is needed to restrict what patterns
are considered ?

**Comment by ngeiswei** [comment] 2016-11-16 10:24
Sure, I don't know exactly where in the code this special filter should be inserted, but I suppose that would be the idea.

**Comment by ngeiswei** [comment] 2016-11-16 10:25
BTW @tanksha have you tried with a lower max gram?

**Comment by tanksha** [comment] 2016-11-16 10:47
Yes I did, and it works.

**Comment by shujingke** [comment] 2017-04-13 18:42
"Start thread 0 from 0 to 4765 " this means thread 0 will process the Link 1~ Link 4765.

**Comment by shujingke** [comment] 2017-04-13 18:47
The test dialogue scm file could contain some structures of Links that are very different from EvaluationLink and InheritanceLink. So far the Pattern Miner only has only been tested on small and huge databases that composed of EvaluationLinks and InheritanceLinks. Theoretically the Types of Links should not matter. But there may some tricky structures I didn't consider before.

**Comment by ngeiswei** [comment] 2018-11-29 13:48
@tanksha, I know it's been a while, but the new pattern miner, see https://github.com/opencog/opencog/blob/master/opencog/learning/miner/README.md, might be able to tackle it.

In any instance this could constitute an interesting test case if it is still relevant to you.

**Comment by linas** [comment] 2019-06-19 05:36
Closing; this appears to have reported a bug in the old pattern miner, the code for which has now been removed.  Please try the new system.

**Closed by linas** 2019-06-19 05:36 UTC
Labels: pattern-miner
