### ISSUE TITLE
Import Error: No module named open cog

### ISSUE THREAD

**Issue by enku-io** [opencog/opencog#3347] opened 2018-11-27 12:26 UTC
I was trying to create a docker image based on `opencog:opencog-deps:latest`. After the build was successful, I tried to import opencog python binding. But I faced an Import Error. I built a docker image based on the same image a few months ago and that image didn't have an import error. Has there been made any breaking changes to the python bindings recently?

**Comment by linas** [comment] 2018-11-27 17:51
Yes, there have been some changes to the python bindings, from @noskill I believe.  However, the unit tests pass, so there is no particular reason to suspect a problem.

I am guessing that this is a python2 vs. python3 problem caused by CMake changes.

I don't know of any easy way of debugging "Import Error" problems.  Compare library names and locations for the working and broken systems. Compare the environment search paths. Use `ldd -r` to determine if there are unresolved symbols in the libraries.

**Comment by AmeBel** [comment] 2018-12-04 09:39
@enku-io the docker image is built against python3

**Comment by Habush** [comment] 2018-12-11 09:10
I am also using `opencog:opencog-deps:latest` as a base image and after trying to import opencog module in the container, it raises an `Import Error`. The python version I am using is 3.6.5

**Comment by AmeBel** [comment] 2018-12-11 09:20
yes because `opencog/opencog-deps` has nothing in it. Use `opencog/opencog-dev:cli`

**Comment by enku-io** [comment] 2018-12-11 11:49
I have tried `opencog/opencog-dev:cli` too. Importing opencog raises the same error. I'm also using python version 3.6.5

**Comment by AmeBel** [comment] 2018-12-12 03:45
Ok then the issue is because the installed atomspace is built against 3.5 and the python package is installed to to python-3.5 dist-directory. Thus, not accessible fro python 3.6.5.
```python
>> docker run --rm -it opencog/opencog-dev:cli
opencog@8f0b0bea4f60:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from opencog.atomspace import AtomSpace, types
>>> dir(AtomSpace)
['__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'add', 'add_link', 'add_node', 'clear', 'get_atoms_by_av', 'get_atoms_by_type', 'get_atoms_in_attentional_focus', 'get_predicates', 'get_predicates_for', 'include_incoming', 'include_outgoing', 'is_valid', 'remove', 'set_truthvalue', 'set_value', 'size']
>>> 
```

**Comment by enku-io** [comment] 2018-12-13 12:35
@AmeBel Thank you for the feedback. It works now. However we use `python 3.6` for our project. When importing atomspace, I face a runtime warning from python saying that compile time version does not match the runtime version of python. Will that cause any problems down the road?

**Comment by linas** [comment] 2019-07-04 16:51
closing, seems to be an python version compatibility bug described in a PEP.

**Closed by linas** 2019-07-04 16:51 UTC
Labels: python
