### ISSUE TITLE
[questions] from an outsider

### ISSUE THREAD

**Issue by LifeIsStrange** [opencog/opencog#3445] opened 2019-02-25 02:52 UTC
Hi!
I am quite fascinated by your approaches on how to build an AGI. 
Still, do you have some state of the art / very promising results on NLU?
What % of Semantic meaning is preserved on the opencog data representation vs an original input of natural langage text?

Where can I access the project roadmap? Work in progresses?

**Comment by linas** [comment] 2019-02-25 04:31
I'm going to close this, as the mailing list is a better forum for general discussions than github issues -- the mailing list reaches a broader audience. The short answer is that I personally have very promising results on NLU; the team assigned to reproduce these results have been unable to do so, and there is a bit of struggle in trying to figure out how to measure "semantic meaning".  

For natural language, I see that you already tripped over `opencog/learn`, and there are several PDF's in there dealing with natural language:

* https://github.com/opencog/opencog/raw/master/learn-lang-diary/skippy.pdf	
* https://github.com/opencog/opencog/raw/master/learn-lang-diary/connector-sets-revised.pdf
* https://github.com/opencog/opencog/raw/master/learn-lang-diary/learn-lang-diary.pdf

There's more on the wiki. There's more from the team that has taken over the language-learning project. For a roadmap -- oof-dah. Ben Goertzel has a bunch of books that might be construed to be a road-map; they will hold up to scrutiny, if you apply the same criteria as you would to a roadmap from Intel, IBM or Apple. 

The original language-learning proposal is here: https://arxiv.org/abs/1401.3372 but I'm quite unhappy with it, as (1) I learned a lot since then, and (2) stuff was written there that I never really liked.  The skippy.pdf, plus some stuff not written down, iss tuff that I'd use as my persona radap, if I had time to actually work on it.

**Closed by linas** 2019-02-25 04:31 UTC

**Comment by linas** [comment] 2019-02-25 04:34
Edit: fixed typos and URL's. see issue.

**Comment by LifeIsStrange** [comment] 2019-02-25 11:47
Thank you a lot for this quality answer, I really appreciate!

BTW you should find me ridiculous, but I think I have an object oriented of a langage in ram representation that allow to make computable every text input I've tried (e.g the Wikipedia page of Apple).
My code not complete but I feel like it most of it could be finished in a month of full time work with only one developer. 
Yes indeed, we can statistically infer that I will fail where every other simplistics projects of mapping human language have failed with far more time and ressources. 
Still, on paper it has no Semantic loss on on paper tested Wikipedia pages.
BTW my very simple early incomplete program has done something than I haven't found on the whole web, it is able to say with 100% of success I a natural language Syllogism is logically valid or logically wrong and where is the error.

I have a failure of imagination of where are the true complexities, 
Could you define what are the main limiting factors?
Exponential complexity? (I don't understund this argument, graph scanning if optimised is 0(1))
Logical checking? (transitivity checking is fairly simple, propositonal logic too, etc)
Coreference resolution? Using state of the art AI mostly solve this problem.
Same for word sense disambiguation and POS tagging. 
Creating Semantic objects with relationships seems feasable.
So why do all projects fails? If no one make a consensus in identifying the issues, we can't progress.
I can't solve a problem I don't understund. 

Second question:
Have you done research and do you have results on argument logical validity automatic checking (cogency and soundness)?
It seems to me like an obvious necessary piece for AGI that no one is working on wtf, also it could revolutionize humanity even without AGI.

Third question:
What do you think of symbolic VS fuzzy AI ?
Or better reframed : of Causality ai vs correlation ai ?

Where can I find the mailing list?

**Comment by linas** [comment] 2019-02-25 19:24
There are two mailing lists: the opencog mailing list, for talking about opencog topics, and the AGI mailing list, for talking about general AGI theories. You will probably find the second mailing list closer to your liking.
