### ISSUE TITLE
Atomspace Benchmark for getHandleSet is borken

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1434] opened 2015-03-18 21:27 UTC
The recent Atomspace changes have made the benchmark show much worse performance. I was getting times about 110 seconds and 900 ops per second after changing shared_mutex to mutex for:

```
./atomspace_bm -m  getHandleSet
```

I was getting times below 90 seconds and ops per second above 1,050 consistently after all my proposed changes. Now I get:

```
Benchmarking AtomSpace's getHandleSet method 100000 times ..........
283.211019 seconds elapsed (353.09 per second)
Sum clock() time for all requests: 248357539 (248.358 seconds, 402.645 requests per second)
```

Compare **248 seconds** to 110 seconds and **402 ops per second** to 900. Something unexpected must be happening.

**Comment by inflector** [comment] 2015-03-18 21:48
Digging into shared_ptr I found this presentation at 4:32

http://channel9.msdn.com/Shows/Going+Deep/C-and-Beyond-2011-Scott-Andrei-and-Herb-Ask-Us-Anything

and this page:

http://herbsutter.com/2013/06/05/gotw-91-solution-smart-pointer-parameters/

to be quite helpful.

**Comment by linas** [comment] 2015-03-19 05:14
Can you relate this to something specific? I measured and got across-the-board 2x or 3x performance improvements.  Viz, before changes:
```
                -g -M -r100    -g -r100   -g -C -r100    -A
   test           memoize       interp      compile    AtomSpace
   name          K-ops/sec     K-ops/sec   K-ops/sec   K-ops/sec
   ----          ---------     ---------   ---------   ---------
  noop               inf         inf          inf       1915
  addNode          101          17.7         97.2        144.4
  addLink          155           5.83       161           93.3
  getType          213          22.9        207          626
  getTV            230          23.6        243          582
  setTV            165          13.2        201          530
  getOutgoingSet   252          24.4        242          596
  getIncomingSet   220          23.8        222          487
  removeAtom        90.2        20.1         77.7        147

```
 after changes:

```
                -g -M -r100    -g -r100   -g -C -r100    -A
   test           memoize       interp      compile    AtomSpace
   name          K-ops/sec     K-ops/sec   K-ops/sec   K-ops/sec
   ----          ---------     ---------   ---------   ---------
  noop               inf         inf          inf       1915
  addNode          121          19.3        104          183
  addLink          232           6.08       262           95.1
  getType          243          25.3        383         1720
  getTV            441          25.5        477         1486
  setTV            249          13.1        249          863
  getOutgoingSet   514          24.6        443         1532
  getIncomingSet   418          24.8        447         1117
  removeAtom       107          21.4        114          161

````

**Comment by linas** [comment] 2015-03-19 05:15
Oh, I see

GetHandleSet -- that test is foobared. You cannot get any valid results for that test, something is deeply wrong there.  The test needs to be fixed first.

**Comment by linas** [comment] 2015-03-19 05:22
and its probably not worth fixing, because last time I looked I think almost no one used that API, anyway, except for some embodiment code that is probably obsolete, and is likely to get replaced by the new OpenPsi work ... 

As I mentioned earlier, the benchmark is rather foobared in a number of ways; not everything it does is valid or correct. The actual elapsed-time counters are implemented incorrecty... its measuring something related to performance, but its not actually measuring actual performance ...

**Comment by inflector** [comment] 2015-03-19 12:42
Ah okay, well unfortunately it is measuring the bottleneck for Python performance pretty well. I'd be happy to fix the benchmark with your suggestions and explore some of the relatively minor changes which will likely improve performance very well. The other benchmarks are doing better because you've likely saved lots of unnecessary resolves which were coming before because of the UUID store.

getHandleSet is measuring only the raw retrieval speed. When, as in the Python case, the only result you care about is the UUID since that is all you can use in Python at the moment, then the extra work involved in storing and retrieving AtomPtrs doesn't buy you anything. It costs you.

I'm pleased the other cases are so much faster, it should be possible to make this one faster too, and probably return it to the same speeds as before.

**Comment by linas** [comment] 2015-03-19 16:55
OK.
1) The python bindings to getHandleByName and getHandlesByType should be removed; the python API for them should never have been created. If there's no API, then no one will be tempted to use them. That would solve the problem :-)

2) one problem with the benchmark is that it calls clock() in a tight loop. That's just bad design, and needs to be fixed.

3) the performance scores to getHandlesByName/ByTtype should be adjusted for how many handles were actually fetched: according to my notes, it says 256K handles, but I'm not sure that's right

4) the correct perf metric for getHandlesByName/ByType should include a dereference after the get: e.g. a getTV on the retrieved atom.  i.e. it is not enough to just get something, but get it, and make sure that its actually in RAM and usable.  This becomes more of an issue for sql or the java graph db, or whatever remote server storage system, where various short-cuts might be tempting.

5) the individual entries in the tests should be adjusted so that they can run for a differng number of iterations.  Currently, the test doesn't run enough loops for things like getType, and too many loops for getHandlesByName/Type

**Comment by linas** [comment] 2015-03-19 17:28
Re the URL's, that you provide about shared pointers: yup.  

To understand the mess, you have to understand some of the history of the atomspace. I've mentioned before this is atomspace version 5.
version 1 used bare pointers, no locks
version 2 used uuids only, no locks
version 3 used uuids and a serialized  global message queue
version X prototype used bare pointers and garbage collection
version 4 used shared_ptr
version 5 adds locks

The problem is that almost all of the code that uses the atomspace dates back to version 1 or 2: it uses handles, instead of atomPtr references. The handles are passed by value, instead of by reference. The atomspace API itself is centered around handles, even though handles are not needed for anything at all except for SQL, and the REST api.

The python API dates back to version 2 -- it is using uuid's instead of atom pointers. 

I had very high hopes for version X, as it would avoid the up-front costs of shared pointers. However, the prototype did not work so well, in particular, with loop-detection and weak pointers. The problem here was that GC and the std::vector, std::set and std::map classes are natural enemies: If std:set has a million items in it, the binary tree might be 20 pointers deep, and the GC is going to give up and stop chasing pointers after about 6 or 8 or 10 steps: its just too expensive.  I think java works around this by storing extra info in the trees, for use by the GC, (not really sure any more),  and scheme is also very careful with weak references. Python uses shared pointers, and I'm not sure what  perl or haskell do.

So, any, I think wee are stuck with shared-pointers, forever and ever. I don't feel so bad about it for two reasons: 1) I recently learned that ref counting and GC are dual.  So the pain is unavoidable.  2) the C++ community has shunned GC and embraced ref counting.  Thus, we can expect future versions of std::vector, std::set std::map to be be more shared-pointer-friendly,

**Comment by linas** [comment] 2015-03-19 17:32
Oh, I forgot:  the upshot is that, over time, we should probably use handles less, and use AtomPtr's more.  

The indexes in the AtomTable can almost sure store naked atom pointers -- there is no need for them to store AtomPtr's, now that I think about it.... The API's would need to be adjusted, however ...

**Comment by linas** [comment] 2015-03-19 18:02
There is one major design decision confronting the atomspace version 6: Should Link store AtomPtr's instead of Handles?  For space reasons, it probably should...  it is hard to imagine under what situations it would be advantageous to hold uuid's.

**Comment by inflector** [comment] 2015-03-31 16:30
Coming back to this again, you mentioned:

>So, any, I think we are stuck with shared-pointers, forever and ever. I don't feel so bad about it for two reasons: 1) I recently learned that ref counting and GC are dual. So the pain is unavoidable.

which I don't understand yet. I understand what you mean by ref counting and GC being dual but not why either is necessary.

I've always used just plain C++ pointer management where one thinks very carefully about who owns what and implements a debug heap allocation system to track down memory leaks should they appear. Memory leak detection is part of debug and tests check for leaks. Etc.

What makes AtomSpace so complicated or different? Couldn't the atoms be owned by the Atomspace until shutdown and just kept around in memory unless explicitly discarded?

If the worry is coming from client user / programmers then perhaps the solution is to provide some nice iterators that guarantee Atoms existence only within the iterator to handle the most typical case where one might be consuming a large number of Atoms only to examine them one by one. For other uses where users require the atoms to exist independently of the AtomSpace, we could create an explicit interface to grab atoms that return AtomPtrs or perhaps we could repurpose the Handle identifier name for that use, i.e. Handles would always indicate shared ownership implemented by an internal AtomPtr shared_ptr. So users would only get Handles when they wanted to keep the Atoms around for a while outside and independent of the AtomSpace.

In this way, atoms would be in one of two pools: either owned or shared, with a small number being shared out of the whole under normal circumstances. Shared atoms would have an associated shared_ptr. Periodically one could sweep the shared list and move any single-reference atoms to the owned pool and remove the shared_ptr overhead automatically. All the internal references within AtomSpace could use bare pointers since AtomSpace would be in control of when Atoms would be deleted / freed, since there would be no circumstances where an external delete would cause an actual delete while AtomSpace still had the Atom since AtomSpace would always have its own shared_ptr reference for any Atoms it owned.

Is there complexity or use cases I haven't seen yet that obviate the above as a viable solution?

**Comment by inflector** [comment] 2015-04-01 18:06
@linas Did you see the above?

**Comment by linas** [comment] 2019-06-19 05:40
closing; this is a stales bug report; the benchmark code does not live in this repo any longer.

**Closed by linas** 2019-06-19 05:40 UTC
Labels: atomspace
