### ISSUE TITLE
Child AtomTable is released later than parent one when using Scheme in Python

### ISSUE THREAD

**Issue by stellarspot** [opencog/opencog#3492] opened 2019-05-15 10:52 UTC
Calling OpenPsi from Python leads to the error (see the code below):
```
terminate called after throwing an instance of 'opencog::RuntimeException'
  what():  AtomTable - deleteing atomtable with subtables! (/home/stellarspot/opencog/master/atomspace/opencog/atomspace/AtomTable.cc:128)
Aborted (core dumped)
```
The problem is that Python releases main atomspace before it releases OpenPsi in Scheme.

Here is what happening during the program execution.

The parent atomspace is created in Python.
GetLink creates child AtomTable (_num_nested is increased to 1) which is stored in the cache when it is not necessary (_num_nested is decreased to 0).

OpenPsi creates OpenPsiImplicator which is a static variable in the `OpenPsiImplicator& opencog::openpsi_implicator()` method.
OpenPsiImplicator extends DefaultPatternMatchCB which grabs the AtomTable from the cache (_num_nested is increased to 1).

When the program finishes Python calls  the main AtomSpace destructor which frees its AtomTable and throws the RuntimeException (the child AtomTable has not been released).

```python
from opencog.type_constructors import *
from opencog.utilities import initialize_opencog, finalize_opencog

# Initialize AtomSpace
atomspace = AtomSpace()
initialize_opencog(atomspace)

PARENT_RECT = ConceptNode("rectangle")
KEY_CORNES = ConceptNode("key-corners")


def add_rect(id, name, x1, y1, x2, y2):
    rect = ConceptNode(name)
    rect.set_value(KEY_CORNES, FloatValue([x1, y1, x2, y2]))
    return SetLink(
        InheritanceLink(rect, PARENT_RECT))


# Called by OpenPsi Action
def find_the_same_rects(params):
    rect1 = params.get_out()[0]
    rect2 = params.get_out()[1]
    # Mark rectangles as handled
    return SetLink(
        EvaluationLink(PredicateNode("handle-rect"), rect1),
        EvaluationLink(PredicateNode("handle-rect"), rect2))


# OpenPsi components

def check_the_same_rects(rect1, rect2):
    if rect1.get_value(KEY_CORNES) == rect2.get_value(KEY_CORNES):
        return TruthValue(1.0, 1.0)
    else:
        return TruthValue(0.0, 1.0)


# OpenPsi context
def context_find_the_same_rects():
    return AndLink(
        InheritanceLink(
            VariableNode("$RECT_1"),
            PARENT_RECT),
        AbsentLink(
            EvaluationLink(
                PredicateNode("handle-rect"),
                VariableNode("$RECT_1"))),
        InheritanceLink(
            VariableNode("$RECT_2"),
            PARENT_RECT),
        AbsentLink(
            EvaluationLink(
                PredicateNode("handle-rect"),
                VariableNode("$RECT_2"))),
        NotLink(
            EqualLink(
                VariableNode("$RECT_1"),
                VariableNode("$RECT_2"))),
        EvaluationLink(
            GroundedPredicateNode("py: check_the_same_rects"),
            ListLink(
                VariableNode("$RECT_1"),
                VariableNode("$RECT_2"))))


# Pass OpenPsi context to Scheme
EvaluationLink(
    PredicateNode("openpsi-context"),
    context_find_the_same_rects())

# Call Scheme
from opencog.scheme_wrapper import scheme_eval

scheme_eval(atomspace,
            '''
            (use-modules
              (opencog)
              (opencog exec)
              (opencog openpsi)
              (opencog python))

            ; OpenPsi Goal
            (define goal
             (Concept "goal"))

            ; OpenPsi Action
            (define action
             (ExecutionOutput
              (GroundedSchema "py: find_the_same_rects")
              (List
               (List
                (Variable "$RECT_1")
                (Variable "$RECT_2")))))

            ; OpenPsi Component
            (define component
             (psi-component "component"))

            ; OpenPsi Context retrieved from Python
            (define context
             (cog-outgoing-set
              (car
               (cog-outgoing-set
                (cog-execute!
                 (Get
                  (Evaluation
                   (Predicate "openpsi-context")
                   (Variable "$CONTEXT"))))))))

            ; OpenPsi rule
            (define rule
             (psi-rule
              context
              action
              goal
              (stv 1 1)
              component))

            ; Run OpenPsi
            (psi-run component)
            (psi-halt component)
            ''')
```

**Comment by stellarspot** [comment] 2019-05-15 12:23
OpenPsiSCM is also created as a static variable in the `void opencog_openpsi_init(void)` method and never destroyed.
It contradicts the fact that a child AtomTable created by  OpenPsiImplicator needs to be released before the parent AtomTable is deleted.

**Comment by linas** [comment] 2019-05-15 20:12
I'm looking now. There is a second, unrelated issue. Doing this:
```
scheme_eval(atomspace,
            '''
            (use-modules
              (opencog)
              (opencog exec)
              (opencog openpsi)
              (opencog python))
''')
```
causes a new atomspace to be created; this is wrong, it should be using the atomspace that python gave it.  However, this is unrelated to your bug (from what I can tell, so far.)

**Comment by linas** [comment] 2019-05-15 21:07
The root cause of the bug is the use of globals in OpenPsi. Specifically, it is this: 

* `OpenPsiImplicator.cc` line 151 creates a static global of `class  OpenPsiImplicator`
* `class  OpenPsiImplicator` inherits from `class Satisfier`
* `class  Satisfier` in `query/Satisfier.h` is meant to be a "temporary" working class that locates answers
* `class  Satisfier` creates instance of `class DefaultPatternMatchCB`
* `class DefaultPatternMatchCB` create temporary scratch atomspaces.

During cleanup:
* `class DefaultPatternMatchCB` (correctly ) releases the temporary atomspaces when its dtored
* the DefaultPatternMatchCB correctly runs when `class Satisfier` dtor runs
* the  `class Satisfier` dtor never runs, because `class  OpenPsiImplicator` is global. Thus, the temp atomspaces are never cleaned up, because the globals are never cleaned up.

**Comment by linas** [comment] 2019-05-15 21:27
The solution would seem to be to split up `class OpenPsiImplicator` into two parts:
 * one part that can correctly process `was_action_executed` -- this part can be safely made into a global.
 * a second part that creates a copy of `class Satisfier` only for a very brief while, to perform the `OpenPsiImplicator::imply()` and the `OpenPsiImplicator::check_satisfiability()` functions, and then deletes `Satisfier` before returning from these two functions.

I'm pretty certain that the performance impact of this would be negligable (if not, let me know)

**Comment by stellarspot** [comment] 2019-05-16 13:26
`OpenPsiImplicator::imply()` and `OpenPsiImplicator::check_satisfiability()` are not called together from one place. They are defined as `psi-satisfiable?` and `psi-imply` scheme functions and seems can be invoked independently  in Scheme using OpenPSI API.

It seems that it is not possible to rely that there are `imply()` call after each `check_satisfiability()` that returns TRUE_TV value. 

One more question that I have should `_satisfiability_cache` and `_pattern_seen` fields be preserved between different Satisfier instances or not.

**Comment by linas** [comment] 2019-05-16 15:46
Those questions are for @AmeBel who wrote the code.

**Comment by stellarspot** [comment] 2019-05-17 13:33
The proposed solution which separates Staisfier from the OpenPsiImplicator: https://github.com/opencog/opencog/pull/3496

**Comment by ferrouswheel** [comment] 2019-06-18 02:54
I came across this issue while working on openpsi and GHOST. My goal is to make both OpenPsi and GHOST resetable without having to completely restart a process.

In addition, for my use-case it'd be nice if only the dynamic state was reset, i.e. inputs and output from handling a conversation. To avoid reloading GHOST rules etc.

From what I've investigated so far, including the issues mentioned here, my current plan is to remove the globals as much as possible. Where a global state is still required, the plan I have is:

- allow openpsi to be initialised on an AtomSpace
- allow openpsi to configure it's working AtomSpace be any descendent of the initialisation AtomSpace
- allow openpsi to free any internal reference of the working AtomSpace so it can the deleted (though ideally it wouldn't hold any internal references)

@stellarspot As you've been making a few changes to OpenPsi, will my above plan clash with what you're working on?

**Comment by stellarspot** [comment] 2019-06-18 08:35
@ferrouswheel 
I have the only last update on the review: #3543
After that the OpenPsi can be refactored in the necessary way.

It would be good if OpenPsi has been updated keeping Python wrapper in mind.
For example some Cython methods need to call scheme because these methods are implemented only on Scheme side:
https://github.com/opencog/opencog/blob/efc88c3f1f19bf02513ad99f9f0a084840b8d2ab/opencog/cython/opencog/openpsi.pyx#L85
It is better to have the common C++ API which can be used both by Scheme and Cython.

**Comment by linas** [comment] 2019-07-04 16:47
Closing, since last comment suggests this was fixed.

**Closed by linas** 2019-07-04 16:47 UTC
Labels: openpsi, python
